### ISSUE TITLE
small request: permission to reproduce examples on wiki.dlang.org

### ISSUE THREAD

**Issue by Laeeth** [vibe-d/vibe.d#1096]
It's really very easy to get powerful stuff done during vibe.d.

But there is a big gap between the examples on the web page and the API documentation (which at this stage often gives hints rather than telling you how to do stuff).  It took me a while to find my way to the examples folder on the repository, and I am more persistent than most - some may give up in frustration before getting to the gratifying part.

Little frictions matter.

So could I have permission to paste the more interesting examples into a page on wiki.dlang.org - this might become the basis for a tutorial in time.

Let me know.

**Comment by s-ludwig** [comment]
Yes absolutely, that wouldn't be a problem.

I'll add a link to the main documentation page as a first step of improvement. This is actually an issue that emerged historically. when vibe.d was started and distributed mainly in terms of Git or zip files, the examples folder was easy to find, but now with DUB it has indeed become quite obscure.

**Comment by csmith1991** [comment]
@Laeeth If you want any help with this I'd be game to help out where I can. I've been meaning to go through them all anyhow, and this might be a good reason to do so.

**Comment by Laeeth** [comment]
Thanks Sonke.

And csmith please feel free to do so - I just felt it a pity that such a superbly useful and pleasant to use library is hard to find examples for (everything is easy when you know how to do it, but until then...)

So maybe the easiest is to set up a page for vibed examples on wiki.dlang.org.  Then we can link to it from appropriate places and put the juiciest examples in other pages (eg I have one or two in the D from Python page).

I won't have so much time immediately, so do make a start if you would like.

**Comment by Geod24** [comment]
@Laeeth : Thanks for improving the docs ! We definitely need to.
@s-ludwig : Just a though, but maybe we can open some kind of meta issue with places that need documentation. That way, people wanting to contribute would have an accessible place to start, and it's a way to get familiar with the functionalities / code.

**Comment by csmith1991** [comment]
@Laeeth: It'd probably be more appropriate to work out of my [user page](http://wiki.dlang.org/User:Csmith1991) and have it reviewed prior to being moved somewhere. I'll be the first to admit I'm not an expert. I also don't have a ton of free time, but I'll contribute where I can.

**Comment by Laeeth** [comment]
Whatever seems best...  More important to start somehow than to wait for perfection.  Thanks.  Laeeth

**Comment by Laeeth** [comment]
http://forum.dlang.org/thread/nrkbicimhhtidsourxpr@forum.dlang.org#post-misuph:241e7p:241:40digitalmars.com

When one first starts using vibed this is a common problem.   Process dies or you kill it but the children keep running.  So a more complete tutorial/faq/set of examples should show how to deal with it.

**Comment by csmith1991** [comment]
I added it to the list of examples [over on my user page](http://wiki.dlang.org/User:Csmith1991/Vibe.d_Documentation). This is something I've had issues with myself, so if I can get some free time, it'd probably be a good one for me to learn from.

I did the websockets one since that was what I've been working on recently anyhow, and figured the  chat client was more of the canonical example compared to a timer running on the server. Now I need to make a write-up for it.

**Comment by Laeeth** [comment]
csmith - love the structured way you are approach it.  looks a very good start.  the more formal setting out of how to do X in Vibed is very helpful.  we should probably also make a friendlier version along the lines of what the chap recently did for D on readthedocs that goes through at a big picture level how to do the commonest things.  'learn vibed in 5 minutes' ;)

what's also missing a bit is how to to common tasks.  for example, I download financial timeseries meta data from quandl, which is json and paged.  I want to send a request, parse the json, get the next page, stick all the results together and return an array or a range with the data.  this is something people doing web stuff often do, but it was a bit painful to figure out.  I wrote the D client API for quandl, so I could probably write it up a bit further.  only thing is that I am not that experienced with D, and my concern is to find a solution that works in a robust way for me, not to write code that the best would be proud of.  so I'll stick it up when time, and others can improve it if they want.

the other thing that is missing is a few complete mini apps (not just snippets like in the examples) from client to server - the whole caboodle.  Javascript is strange and alien to me, so I am not familiar with what is done in that field.  But I think the Dart docs are pretty good, and perhaps we should aim at doing something similar.

we can probably nick parts of the dlang.org and vibed.org website/blog/userman code bases.  it's just too overwhelming if you don't yet know D or vibed to dive into them, but one can carve out some useful snippets and write them up in a friendly way.  it's the right approach to do it slowly when one has time, since it's too much to do in one go.

some examples of D generating javascript directly might also be nice.

I like diet templates very much for my purposes, but they are not so easy to figure out from the docs.  'heres a starter, and look at the Jade docs if you get stuck'.  more examples here would be good.

**Comment by Laeeth** [comment]
http://wiki.dlang.org/Vibed_faq_addition here is a start

**Comment by Geod24** [comment]
Cleaning up old issues, closing as there is nothing actionable left to do. Another great example of why it'd be nice to have "Discussions" enabled (see #2461 ).
