### ISSUE TITLE
runEventLoop always returns 0 and never logs the event driver eventLoop error code

### ISSUE THREAD

**Issue by roberto-delfiore** [vibe-d/vibe.d#1223]
From vibe.core.core.runEventLoop:
....

```
if (auto err = getEventDriver().runEventLoop() != 0) { // *
    if (err == 1) { // **
        logDebug("No events active, exiting message loop.");
        return 0;
    }
    logError("Error running event loop: %d", err);   // *** 
    return 1;
}

logDebug("Event loop done.");
return 0;
```

}

// \*   The comparison operator has higher priority than the assignment operator, so err is a bool
// *\*  true == 1 is true :)
// **\* This branch is never executed.

**Comment by Geod24** [comment]
Thanks for the report! Just checked, this is not an issue anymore: https://github.com/vibe-d/vibe-core/blob/e7d9e7ed9ed055d4be01aeee4551289eafbf6440/source/vibe/core/core.d#L218-L225
