### ISSUE TITLE
connectTCP could crash if it was interrupted (libevent driver)

### ISSUE THREAD

**Issue by japplegame** [vibe-d/vibe.d#1331]
Assertion point - https://github.com/rejectedsoftware/vibe.d/blob/v0.7.26/source/vibe/core/drivers/libevent2_tcp.d#L648

Looks like it happens when connection is actually established  but right before dispatching `onSocketEvent` the vibe.d core interrupts the task, throws InterruptException, which is caught here - https://github.com/rejectedsoftware/vibe.d/blob/v0.7.26/source/vibe/core/drivers/libevent2.d#L311. `TCPContext` is destroyed and after that `onSocketEvent` called by libevent with wrong context.

Such a situation seems very unlikely, but in the real world we are confronted with it every few days.
We use something similar to this code:

``` d
auto current = Task.getThis;
auto timer = setTimer(timeout, &current.interrupt);
try {
    scope(exit) timer.stop();
    requestHTTP(...);
} catch(InterruptException exception) {
    throw new Exception("task timed out");
}
```

**Comment by japplegame** [comment]
Can anyone help me?
These crashes occur more often as load growth.

**Comment by s-ludwig** [comment]
I've added a fix on master, can you verify if it works for you?

**Comment by japplegame** [comment]
Thank you. I'll try it.

**Comment by japplegame** [comment]
Interrupted connection crash was fixed, but another crash introduced (most likely by commit #1331).
Trying to connect with a non-listening address causes a crash:
```
Task terminated with uncaught exception: Failed to connect to 127.0.0.1:8080: Error reading from socket 9 (Connection refused)                                                                
[err] bufferevent.c:611: Assertion bufev_private->refcnt > 0 failed in _bufferevent_decref_and_unlock
```
Code
```d
import vibe.d;

shared static this() {
	runTask({
		requestHTTP("http://127.0.0.1:8080",
			(scope HTTPClientRequest req) {},
			(scope HTTPClientResponse res) {}
		);
	});
}
```

**Comment by japplegame** [comment]
Ping
