### ISSUE TITLE
Cannot serialize std.uuid.UUID

### ISSUE THREAD

**Issue by clinei** [vibe-d/vibe.d#1383]
Reduced: http://dpaste.dzfl.pl/df95fe9c2082

```
import vibe.data.bson : serializeToBson;
import std.uuid : randomUUID;
serializeToBson(randomUUID()); // Error: argument 8 has no protection
```

The cause is `__traits(getProtection, MEM)` from [vibe.internal.meta.traits.isPublicMember](https://github.com/rejectedsoftware/vibe.d/blob/master/source/vibe/internal/meta/traits.d#L243)

"8" is from [std.uuid.UUID.skipSeq](https://github.com/D-Programming-Language/phobos/blob/master/std/uuid.d#L132)

The problem is that `isPublicMember` tries to check if a tuple has protection.
The solution might be to define `isPublicMember` as `false` if `MEM` is a tuple (I have no idea how to do that).

**Comment by denizzzka** [comment]
https://github.com/rejectedsoftware/vibe.d/pull/1404

**Comment by denizzzka** [comment]
This issue is still actual?

**Comment by wilzbach** [comment]
Works fine for me with Vibe.d 0.8.2
