### ISSUE TITLE
dub build -b unittest fails (windows)

### ISSUE THREAD

**Issue by tchaloupka** [vibe-d/vibe.d#1439]
Noticed today with vibe 0.7.27
Tried with DMD2.070.0 and latest 2.070.1 beta
I'm on Windows 8.1 64bit

Just do

```
dub init test vibe.d
dub build -b unittest
```

It fails with:

```
Linking...
OPTLINK (R) for Win32  Release 8.00.17
Copyright (C) Digital Mars 1989-2013  All rights reserved.
http://www.digitalmars.com/ctg/optlink.html
.dub\build\application-unittest-windows-x86-dmd_2070-333D59EB792BC4DA878B612E7F0234E2\testv.obj(testv)
 Error 42: Symbol Undefined _D3std8typecons15__T8NullableTiZ8Nullable6__initZ
--- errorlevel 1
dmd failed with exit code 1.
```

I'm not sure if this is some problem with DMD or Vibe.d :(

When tried with `--combined` switch
It ends up with (can be caused by out of memory with 32bit DMD?):

```
Unexpected OPTLINK Termination at EIP=0040347E
EAX=00000010 EBX=00000004 ECX=00000000 EDX=004337CF
ESI=0044AAE8 EDI=00000100 EBP=0018FF4C ESP=0018FDE4
First=00402000
```

**Comment by Geod24** [comment]
This was good old optlink. Closing as there's nothing Vibe can do here (and it's likely fixed, as AppVeyor tests on Windows).
