### ISSUE TITLE
difference bw std.json.JSONValue and vibe.data.json.Json ? any conversion function?

### ISSUE THREAD

**Issue by timotheecour** [vibe-d/vibe.d#1465]

**Comment by s-ludwig** [comment]
Yes, should probably be added, as well as `stdx.data.json.value.JSONValue`. The difference is mostly their API (which became more similar after recent improvements to `std.json`), storage-wise they are very similar.

**Comment by lionello** [comment]
Just to add a +1: this is the biggest hurdle when moving from NodeJS to D. Vibe.D is awesome, but non-Vibe.D projects use std.json and you're left confused between what to use when.

A conversion function is nice, but won't solve the problem of having to mess with two different APIs, with different semantics and behaviors. The only way forward is to move to one JSON type in D and get it accepted in Phobos.
