### ISSUE TITLE
Improve and test Websocket

### ISSUE THREAD

**Issue by Geod24** [vibe-d/vibe.d#1505]
Following recent discussions, just creating an issue to track that.
There seem to be an obvious test suite for websockets: https://github.com/crossbario/autobahn-testsuite
AFAICS, the module code quality could be improved, and so could the documentation. Finally, ping/pong from the client side looks broken.

**Comment by Geod24** [comment]
@s-ludwig : Might be a bit early to ask, but would you consider a split into two module (client/server, as HTTP does) ?

**Comment by s-ludwig** [comment]
I guess it depends on the size of the API. If it becomes necessary just because of implementation size, I'd rather go for a `http.internal` package (same rationale as for `web.internal`.

**Comment by Geod24** [comment]
My original thought was that it could be worthwhile to separate client and server.
However, since it's a bidirectional connection, and after another half day of fiddling, I'd rather wait a bit.

The current client approach seems to rely on the implementer knowing which kind of message it receives - binary or text -.  I don't know how well that assumption will do in the real world, but as part of testing, I'd like a way to dispatch binary and text message to separate method, and it's not there. From a quick look, the same issue seems present in the server as well.

For reference, this is the kind of API Java provides: https://github.com/crossbario/autobahn-android/blob/e5abf7c64c9327ff2515a831d4e6125f716b69ee/Demo/TestSuiteClient/src/de/tavendo/autobahn/testsuiteclient/MainActivity.java#L104-L126

**Comment by Geod24** [comment]
Solved in #1534
