### ISSUE TITLE
Provide a 'main' task function ?

### ISSUE THREAD

**Issue by Geod24** [vibe-d/vibe.d#1517]
This is more of an idea than an actual request, just throwing it here to see what you think about it.

Quite often, when I write client code, I end up with the following:

``` D
shared static this () { runTask(() => mainTask); }

void mainTask ()
{
    // Do stuff
}
```

Because I don't want to go through the hassle of defining my own main, but I still want the event loop.
However, there is currently no way to get the arguments when this is used, and that's the only thing missing to be able to quickly write tools using Vibe.d.

Is there already a way to do it ? Do you have some plans for arguments handling in general ?

**Comment by s-ludwig** [comment]
There is <http://dlang.org/library/core/runtime/runtime.args.html>, which is also used by the `vibe.core.args` module. A built-in way to invoke such a `mainTask` would also be interesting, but is there any seamless way other than requiring it to be `extern(C)`?

**Comment by Geod24** [comment]
Closing since nowadays `VibeDefaultMain` is the default.
