### ISSUE TITLE
REST service with struct as a parameter - memleak?

### ISSUE THREAD

**Issue by tchaloupka** [vibe-d/vibe.d#1588]
Lets have:

``` D
struct Foo {
    long id;
    string name;
    @optional Foo[] foos;

    ~this() { writeln("~this"); }
}

interface MyAPI {
    void addFoo(Foo[] foos);
}

class MyAPIImplementation : MyAPI {
    void addFoo(Foo[] foos) {
        writeln("addFoo ", foos.length);
    }
}

shared static this() {
    auto router = new URLRouter;
    router.registerRestInterface(new MyAPIImplementation);

    auto settings = new HTTPServerSettings;
    settings.port = 8080;
    listenHTTP(settings, router);
}
```

If requested with for example

```
curl -v http://localhost:8080/foo -H "Content-Type: application/json" -d '{"foos":[{"id":1,"name":"test 1"},{"id":2,"name":"test 2","foos":[{"id":21,"name":"test 21"}]}]}'
```

Destructor of the Foo struct is not called after the request is processed.

Is this the expected behavior? We are having some memory leak problem in our service and this is one of the problems we found.

**Comment by s-ludwig** [comment]
I haven't followed the latest GC developments, but while `new S` has been fixed to call the destructor when the object gets collected, I *think* that this is still not the case for dynamic arrays. It would of course be possible to manually destroy the array within `vibe.web`, but that would mean that it can't be stored without `.dup`ing it.

The best workaround for now seems to be to explicitly `destroy(foos);` at the end of the callback.

**Comment by s-ludwig** [comment]
Thinking about it some more, how about that if `vibe.web` detects a struct with a destructor, it checks for the presence of either the `scope` attribute, or a `@manualDestroy` (or a better name) UDA. If `scope` is present, it automatically calls `destroy`. If `@manualDestroy` is present, it will assume that the callback destroys it. Otherwise, it will issue a compile-time warning, mentioning the possible leak.

**Comment by tchaloupka** [comment]
I think, that this is no longer an issue. Tried it again with:

```D
#!/usr/bin/env dub
/+ dub.sdl:
	name "memleak"
	dependency "vibe-d:web" version="~>0.8.5-beta.1"
+/

import core.memory;
import core.time;
import std.stdio;
import vibe.core.core;
import vibe.data.serialization;
import vibe.http.router;
import vibe.http.server;
import vibe.web.rest;

@safe:

struct Foo {
	long id;
	string name;
	@optional Foo[] foos;

	~this() { writeln("~this"); }
}

interface MyAPI {
	void addFoo(Foo[] foos);
}

class MyAPIImplementation : MyAPI {
	void addFoo(Foo[] foos) {
		writeln("addFoo ", foos.length);
	}
}

void main()
{
	auto router = new URLRouter;
	router.registerRestInterface(new MyAPIImplementation);

	auto settings = new HTTPServerSettings;
	settings.port = 8080;
	auto l = listenHTTP(settings, router);
	scope (exit) l.stopListening();

	setTimer(1.seconds, () @trusted { GC.collect();}, true);

	runApplication();
}
```

So GC is explicitly called to be sure it cleans it and it does.
Tried with dmd 2.082.0
Closing this
