### ISSUE TITLE
ld: warning: directory not found for option '-L/usr/local/opt/openssl/lib'

### ISSUE THREAD

**Issue by timotheecour** [vibe-d/vibe.d#1637]
my project stopped compiling today with `ld: warning: directory not found for option '-L/usr/local/opt/openssl/lib'`;
hard to tell what changed but `mdfind /usr/local/opt/openssl/lib` indicates the only source of this is from `vibe.d/stream/dub.sdl` which contains a hardcoded path:
```
lflags "-L/usr/local/opt/openssl/lib" platform="osx"
```

I'm using homebrew installed in $HOME and libssl is under `$HOME/homebrew/opt/openssl/lib/libssl.dylib` for me

it used to work fine until today (even for vibe.d applications).

**Comment by Geod24** [comment]
Did you by any chance update `ld` ?
Usually `ld` doesn't fail if a directory is not present (same for compilers, they just ignore missing include directory).

**Comment by timotheecour** [comment]
indeed these were just warnings, the actual error was unrelated (ld: file not found:) and was my fault (https://github.com/dlang/dub/issues/1003);
still though, do we want this hardcoded path?

**Comment by s-ludwig** [comment]
Removing the hardcoded path would be good. The question just is how to find OpenSSL in a dynamic way on the latest macOS.

**Comment by timotheecour** [comment]
could you use HOMEBREW_ROOT environment variable as done in
https://github.com/gtkd-developers/GtkD/commit/0e8b34e0be0d8a7d9e5b24857f7366fdd2ee7adc
for a similar purpose?

**Comment by s-ludwig** [comment]
On my system, `HOMEBREW_ROOT` doesn't appear to be set, so what I could do is to add both, the current path and the dynamic one with `$HOMEBREW_ROOT`. That would of course still issue the warning, but at least it should work in all cases then.

Do you know by chance where `HOMEBREW_ROOT` is being set, or why it might not be set in my case?

**Comment by timotheecour** [comment]
Homebrew wont mess with your environment variables, the user sets it
(because u can have multiple homebrew installs)

**Comment by Robert-M-Muench** [comment]
Building the most simple vibe app, looks like I have the same problem on OSX:

```
Linking...
ld: warning: directory not found for option '-L/usr/local/opt/openssl/lib'
ld: warning: directory not found for option '-L/usr/local/opt/openssl/lib'
ld: warning: directory not found for option '-L/usr/local/opt/openssl/lib'
ld: warning: directory not found for option '-L/usr/local/opt/openssl/lib'
ld: warning: directory not found for option '-L/usr/local/opt/openssl/lib'
ld: warning: directory not found for option '-L/usr/local/opt/openssl/lib'
Undefined symbols for architecture x86_64:
  "_CRYPTO_num_locks", referenced from:
      __D4vibe6stream7openssl26_sharedStaticCtor_L1084_C1FZv in libvibe-d_tls.a(openssl.o)
  "_CRYPTO_set_id_callback", referenced from:
      __D4vibe6stream7openssl26_sharedStaticCtor_L1084_C1FZv in libvibe-d_tls.a(openssl.o)
  "_CRYPTO_set_locking_callback", referenced from:
      __D4vibe6stream7openssl26_sharedStaticCtor_L1084_C1FZv in libvibe-d_tls.a(openssl.o)
  "_SSL_get_ex_new_index", referenced from:
      __D4vibe6stream7openssl26_sharedStaticCtor_L1084_C1FZv in libvibe-d_tls.a(openssl.o)
  "_SSL_library_init", referenced from:
      __D4vibe6stream7openssl26_sharedStaticCtor_L1084_C1FZv in libvibe-d_tls.a(openssl.o)
  "_SSL_load_error_strings", referenced from:
      __D4vibe6stream7openssl26_sharedStaticCtor_L1084_C1FZv in libvibe-d_tls.a(openssl.o)
  "_SSLv23_client_method", referenced from:
      __D4vibe6stream7openssl14OpenSSLContext6__ctorMFNfEQBwQBu3tls14TLSContextKindEQCxQCvQBb10TLSVersionZ9__lambda3MFNbNeZv in libvibe-d_tls.a(openssl_135_569.o)
  "_SSLv23_server_method", referenced from:
      __D4vibe6stream7openssl14OpenSSLContext6__ctorMFNfEQBwQBu3tls14TLSContextKindEQCxQCvQBb10TLSVersionZ9__lambda3MFNbNeZv in libvibe-d_tls.a(openssl_135_569.o)
  "_get_rfc3526_prime_2048", referenced from:
      __D4vibe6stream7openssl14OpenSSLContext11setDHParamsMFNeAyaZv in libvibe-d_tls.a(openssl_135_569.o)
  "_sk_num", referenced from:
      __D6deimos7openssl9safestack__T10SKM_sk_numTSQBqQBm6x509v315GENERAL_NAME_stZ__TQBwZQCaFNbPSQDkQDgQDb__T8STACK_OFTQCrZQoZi in libvibe-d_tls.a(safestack_3c8_449.o)
     (maybe you meant: __D6deimos7openssl9safestack__T10SKM_sk_numTSQBqQBm6x509v315GENERAL_NAME_stZ__TQBwZQCaFNbPSQDkQDgQDb__T8STACK_OFTQCrZQoZi)
  "_sk_value", referenced from:
      __D6deimos7openssl9safestack__T12SKM_sk_valueTSQBsQBo6x509v315GENERAL_NAME_stZ__TQByZQCcFNbPSQDmQDiQDd__T8STACK_OFTQCrZQoiZPQDa in libvibe-d_tls.a(safestack_3ca_516.o)
     (maybe you meant: __D6deimos7openssl9safestack__T12SKM_sk_valueTSQBsQBo6x509v315GENERAL_NAME_stZ__TQByZQCcFNbPSQDmQDiQDd__T8STACK_OFTQCrZQoiZPQDa)
ld: symbol(s) not found for architecture x86_64
```

I grepped the hardcoded path in:
```
vibe-d-0.8.6/vibe-d/tls/dub.sdl
6:lflags "-L/usr/local/opt/openssl/lib" platform="osx"
``` 
but '/usr/local/opt/...' doesn't exists on my system. I'm using MacPorts which installed into '/opt/local/lib'. 

Is there a way to make this more flexible by adding more default paths, for MacPorts, etc.?

**Comment by Robert-M-Muench** [comment]
* Looks like the "-L..." is wrong and needs to be removed.
* I replace the line with `lflags "/opt/local/lib" platform="osx" to the SDL file

Which now makes it a bit further but fails with this:

```
ld: can't map file, errno=22 file '/opt/local/lib' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: linker exited with status 1
```

**Comment by Robert-M-Muench** [comment]
Building on Windows works.

**Comment by Robert-M-Muench** [comment]
Ok, and this all drills down to vide.d defaulting to OpenSSL 1.0. Using:

`dub build --override-config vibe-d:tls/openssl-1.1` and having the hard-coded `lflags`option commented, works on OSX too.

**Comment by Geod24** [comment]
The warning itself is harmless (or should be). It just means one of the import path given to LD doesn't exists. If you use v0.8.6, Vibe.d just won't link on OSX. Use either master or the latest beta, and it should work. The release is very overdue at this point. @s-ludwig any ETA ?

**Comment by Geod24** [comment]
A release was made and this was fixed.
