### ISSUE TITLE
Running a vibe-d app with --DRT-gcopt=profile:1 fails

### ISSUE THREAD

**Issue by grogancolin** [vibe-d/vibe.d#1656]
I can't pass `--DRT-gcopt` to my vibe-d application.
 
```
Unrecognized command line option: --DRT-gcopt=profile:1
```

This is using a custom main function with:
```	// returns false if a help screen has been requested and displayed (--help)
	if (!finalizeCommandLineOptions())
		return;
	lowerPrivileges();
	runEventLoop();
```

**Comment by grogancolin** [comment]
Hmm, removing `if (!finalizeCommandLineOptions)` allows the options to pass down to the runtime.

That function might need to recognize D runtime specific options.

**Comment by mathias-lang-sociomantic** [comment]
Will be fixed by https://github.com/vibe-d/vibe.d/pull/1944
