### ISSUE TITLE
Please fix the Meson build configuration

### ISSUE THREAD

**Issue by ximion** [vibe-d/vibe.d#1702]
Hi!
Vibe.d is now a proper package in Debian, ready to install & use: https://packages.debian.org/source/sid/vibe.d
Since dub doesn't work for packaging, we rely on Meson to build the package right now (with [one patch](https://sources.debian.net/src/vibe.d/0.7.30-1/debian/patches/01_include-batch-install.patch/)).

To get a more recent version packaged in future, the Meson build configuration needs to be up-to-date. I would submit a patch, but I have no idea yet where the repository is going (with all the splitting) and what makes sense there.

So, this bug is more a todo item, so this issue isn't forgotten ;-)

P.S: Hooking up Travis and Meson/D should work now, since LDC is fixed with it's latest release.

**Comment by s-ludwig** [comment]
So the long-term plan is to replace this repository with multiple separate repositories/packages. These packages will correspond to the current sub packages except for `vibe-d:textfilter`, which will be split further, so that there is a separate markdown module.

The pace at which these splits will happen will probably not be too high. After the ["vibe-core"](https://github.com/vibe-d/vibe-core) module is mostly done now (replacing "vibe-d:core"), next up is the "vibe-http" module which will take a while. ["diet-ng"](https://github.com/rejectedsoftware/diet-ng/) is already done and already replaces "vibe-d:templ".

It probably makes sense to restrict the Debian package to the 0.7.x branch for now, which isn't affected by these change yet (except for the "diet-ng" separation). I'll maintain that for a while (only bugfixes), until 0.8.x is considered fully stable.

BTW, this is great news! I'll have to try this out as soon as possible to get a better feel for how this fits together with everything else.

**Comment by ximion** [comment]
> So the long-term plan is to replace this repository with multiple separate repositories/packages

Eww, a lot of work at Debian ^^ - but it's a good idea. One of my biggest issues with D is that it's standard library is really bad compared to what other languages have to offer, and Vibe provides a lot of useful primitives that are useful even without the webserver (MongoDB driver, template system, data serialization, ...)

> It probably makes sense to restrict the Debian package to the 0.7.x branch for now, which isn't affected by these change yet (except for the "diet-ng" separation). I'll maintain that for a while (only bugfixes), until 0.8.x is considered fully stable.

Nice! The Vibe package wasn't uploaded in time to get into the next Debian release, but in future it would be useful to have such "LTS"-like releases in the releases, to simplify backporting security fixes.

> BTW, this is great news! I'll have to try this out as soon as possible to get a better feel for how this fits together with everything else.

I am using Vibe.d for [Laniakea](https://github.com/lkorigin/laniakea) a currently experimental project to make building Debian derivatives easier (when done, it will do a large amount of maintenance tasks). It is used by [Tanglu](http://tanglu.org/) and [PureOS](https://pureos.net/), and the latter is sponsoring its development. This project is the primary reason for me wanting Vibe easily accessible in Debian and Ubuntu (since Laniakea should also be available there when it's more mature).
I am no web developer though, I usually do low-level C stuff, and I must say that I am very impressed by Vibe - it is incredibly easy to use and very fast. I was using Python+Flask for projects like this before, so using D+Vibe is something new. There are some scary stories on the forums about Vibe applications slowing down over time or getting killed because the GC takes more than 2 seconds to run a collection cycle, so I hope we don't run into any of these issues - so far, my first steps in writing web apps with Vibe have been very smooth, and Vibe's API is really really good. So, kudos and thanks for your work!

RE Meson, there are a few annoyances, e.g. the pkg-config files do not declare their dependencies properly since we use the very simple built-in generator for these files, that should be changed at some point (although I hope Meson upstream will make their pkg-config generator a bit more powerful).
The other issue is that one explicitly needs to pass-in `appmain.d` to be compiled directly into the source code, and then submit `-d-version=VibeDefaultMain` manually: https://github.com/lkorigin/laniakea/blob/master/src/web/meson.build#L14
This could in theory be encapsulated into an optional pkg-config file, the problem here is though that the different D compilers all have a different flag to pass in a D version, which makes this really messy and might even require dedicated support for in Meson or some hackish script to adjust flags for the right compiler (I would be so much happier if all D compilers would just use the GNU compiler flags, like GCC and Clang do).
Needing to pass the `-J` flag manually is okay for now, I think.

Apart from these (solvable, except for the command-line flags thing) issues, Vibe works great with Meson. I added https://github.com/rejectedsoftware/vibe.d/pull/1720 to fix a few issues in the stable branch's Meson file and have the build tested by Travis.
While doing that I also encountered some issues that I'll have to raise at Meson.

**Comment by denizzzka** [comment]
bump

**Comment by Geod24** [comment]
There is now https://github.com/vibe-d/vibe.d/blob/master/scripts/tag_version.sh which is used to ensure that the meson file stays up to date. Closing.
