### ISSUE TITLE
Support for options parameter in MongoCollection.aggregate

### ISSUE THREAD

**Issue by tetianakh** [vibe-d/vibe.d#1718]
Mongodb `db.collection.aggregate`[ accepts 2 parameters](https://docs.mongodb.com/manual/reference/method/db.collection.aggregate/):  aggregation pipeline, and options. I need to set `{allowDiskUse: true}` for my aggregation pipelines, but as far as I can tell from the source and the documentation, `MongoCollection.aggregate` accepts only aggregation pipeline, and there's no way to pass the second argument. 

Is there a way to pass the `options` argument to the  `MongoCollection.aggregate`?

**Comment by pete-fab** [comment]
Hi.
I have the same issue. Is there a way to pass `options` into `MongoCollection.aggregate`?
