### ISSUE TITLE
HTTPClientResponse body without Content-Length

### ISSUE THREAD

**Issue by tchaloupka** [vibe-d/vibe.d#1780]
A came across an embedded server (Axis camera) which returns this:

```
HTTP/1.0 200 OK
Keep-Alive: timeout=2, max=100
Connection: Keep-Alive
Allow: OPTIONS, GET, HEAD, POST, PUT, DELETE, TRACE
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS, GET, HEAD, POST, PUT, DELETE, TRACE
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
Content-Type: text/xml
Status: 200 OK

<events>
....
</events>
```

And with vibe-d, the response body cannot be read (it creates the stream with limited size set to 0).
It seems to be a problem with combination of Connection: Keep-Alive (which is returned even if not requested) and missing Content-Length - so probably a bug on the server side.

But with std.net.curl it is readed fine, and for example with VSCode REST Client extension too.
Is there some way to read it with vibe?

**Comment by s-ludwig** [comment]
I guess this needs a hack to ignore the `Connection: Keep-Alive` for `HTTP/1.0` and assume `Connection: close` instead. It looks like that is the overall more robust approach.
