### ISSUE TITLE
redis auth support in vibe.db.redis.redis.connectRedisDB(...)

### ISSUE THREAD

**Issue by qwertzui11** [vibe-d/vibe.d#1896]
Hi, great library! thx for your work!

there's an open `// TODO: support password` at 
https://github.com/rejectedsoftware/vibe.d/blob/master/redis/vibe/db/redis/redis.d#L47
that simply could get resolved by replacing the TODO with
```cli.auth(url.password);```
In my opinion that would improve the usability a lot, eg with heroku and the chat tutorial.
```
string url = environment.get("REDIS_URL") ~ "/0";
RedisDatabase db = connectRedisDB(URL(url));
```
What do you think? If want, I can open a pull request.

**Comment by s-ludwig** [comment]
That makes sense! There is already a pull request open that addresses this together with a few other possibilities: #1842 - It got a bit lost in the queue, but I'll try to get back to it as soon as possible.

**Comment by qwertzui11** [comment]
Thanks a lot, if I can do anything to help you out, let me know! :smiley:

**Comment by wilzbach** [comment]
FYI apart from #1842 there's also the convenience PR for using strings too: https://github.com/vibe-d/vibe.d/pull/1852
