### ISSUE TITLE
can't build 0.8.1 while 0.8.0 is working fine (32 bit only Windows bug)

### ISSUE THREAD

**Issue by bubnenkoff** [vibe-d/vibe.d#1910]
dmd 2.076-rc1.

See screenshots:
![123](https://user-images.githubusercontent.com/6514326/29971989-3292323a-8f33-11e7-9acc-9a7c0395e6d1.png)
![1231](https://user-images.githubusercontent.com/6514326/29972002-3dc6d8f4-8f33-11e7-973e-fe70cc6bea19.png)

with `dub --arch=x86_64` both versions works fine

**Comment by bubnenkoff** [comment]
https://github.com/etcimon/libasync/issues/81

**Comment by asampal** [comment]
I'm seeing this with 64 Windows - is the title correct?

**Comment by Computermatronic** [comment]
There is a nasty bug somewhere deep in Optlink ([https://issues.dlang.org/show_bug.cgi?id=17508](url)) that causes this, and it effects all subsequent versions of vibe.d since 0.8.1. Building with the mscoff32 flag or using LDC works fine.

**Comment by Geod24** [comment]
Optlink is not used by default anymore, so this external bug should not reproduce (by default).
