### ISSUE TITLE
`dub test --coverage --combined` fails for vibe-d:tls with botan

### ISSUE THREAD

**Issue by tom-tan** [vibe-d/vibe.d#1920]
The following command fails on Linux 64bit with dmd 2.076.0.
Is there a way to workaround this issue?

```
$ git clone git@github.com:vibe-d/vibe.d.git
$ cd vibe.d/tls
$ dub test -c botan --coverage --combined
...
../../../.dub/packages/botan-1.12.9/botan/source/botan/math/numbertheory/pow_mod.d(170,1): Error: class botan.math.numbertheory.pow_mod.FixedExponentPowerModImpl is forward referenced when looking for 'opDollar'
dmd failed with exit code -11.
```

We have to use `--combined` option for coverage test for vibe-d due to [Issue 13742 in dmd](https://issues.dlang.org/show_bug.cgi?id=13742) (See also #767).
OTOH we cannot run coverage test for botan (vibe-d:tls depends on it) with `--combined` option because it fails with the above error message.
As a result we cannot run coverage test for vibe-d:tls package when we use botan library.

There is an alternative to use OpenSSL (it is the default option for vibe-d:tls) instead of botan for vibe-d:tls but there is another issue about library compatibility for libssl (See #1758).
I know `VibeUseOpenSSL11` to solve #1758 but I do not want to care about the version of OpenSSL in the target system.
That is the reason why I try to use botan instead of OpenSSL.

I open this issue in vibe.d instead of botan because I do not know much about `--combined` option and because I'm not sure botan should support `--combined` option.
In my understanding, `--combined` is introduced for the workaround of issue 13742 and it is not intended that all library should support this option.

**Comment by Geod24** [comment]
I assume most of this, if not all, is now fixed (e.g. the DMD issue is). However I could not test it properly because of #2578 .
Moving the conversation there as it has up-to-date informations.
