### ISSUE TITLE
sample/future throw exception

### ISSUE THREAD

**Issue by mzfhhhh** [vibe-d/vibe.d#1982]
vibe-d-0.8.1
compile and run "sample/future",it throw exception:

Running .\future-example.exe
Starting to compute value.
Starting computation in main task
Finished computation in main task. Waiting for async value.

core.exception.AssertError@..\..\core\vibe\core\core.d(1330): Joining tasks in f
oreign threads is currently not supported.

**Comment by dhasenan** [comment]
Duplicate of https://github.com/vibe-d/vibe.d/issues/1521

**Comment by s-ludwig** [comment]
The joining functionality has been implemented for vibe-core and this works corretly now on master. Closing this and the other issue.
