### ISSUE TITLE
wrong log time

### ISSUE THREAD

**Issue by zafer06** [vibe-d/vibe.d#1989]
I want to write the logs to the file and I set setLogFile() but log hour is wrong.

OS: Linux Mint 18.1
Vibe: vibe/0.8.2-rc.1

```D
import vibe.vibe;

void main()
{
	setLogLevel(LogLevel.trace);
	setLogFormat(FileLogger.Format.threadTime);

	auto settings = new HTTPServerSettings;
	settings.port = 8080;
	settings.bindAddresses = ["::1", "127.0.0.1"];
	listenHTTP(settings, &hello);

	logInfo("Please open http://127.0.0.1:8080/ in your browser.");

	logInfo("************ Current Time : %s ************",
		Clock.currTime.toSimpleString());

	runApplication();
}

void hello(HTTPServerRequest req, HTTPServerResponse res)
{
	res.writeBody("Hello, World!");
}
```

> zafer@zafer-pc /media/depo/Projeler/genel/vibe-log $ dub run
> Performing "debug" build using dmd for x86_64.
> vibe-d:utils 0.8.2-rc.1: target for configuration "library" is up to date.
> vibe-d:data 0.8.2-rc.1: target for configuration "library" is up to date.
> vibe-d:core 0.8.2-rc.1: target for configuration "libevent" is up to date.
> vibe-d:crypto 0.8.2-rc.1: target for configuration "library" is up to date.
> diet-ng 1.4.3: target for configuration "library" is up to date.
> vibe-d:stream 0.8.2-rc.1: target for configuration "library" is up to date.
> vibe-d:textfilter 0.8.2-rc.1: target for configuration "library" is up to date.
> vibe-d:inet 0.8.2-rc.1: target for configuration "library" is up to date.
> vibe-d:tls 0.8.2-rc.1: target for configuration "openssl" is up to date.
> vibe-d:http 0.8.2-rc.1: target for configuration "library" is up to date.
> vibe-d:mail 0.8.2-rc.1: target for configuration "library" is up to date.
> vibe-d:mongodb 0.8.2-rc.1: target for configuration "library" is up to date.
> vibe-d:redis 0.8.2-rc.1: target for configuration "library" is up to date.
> vibe-d:web 0.8.2-rc.1: target for configuration "library" is up to date.
> vibe-d 0.8.2-rc.1: target for configuration "libevent" is up to date.
> vibe-log ~master: building configuration "application"...
> Linking...
> To force a rebuild of up-to-date targets, run again with --force.
> Running ./vibe-log 
> [9E131F8D:00000000 2017.11.30 12:06:57.141 dbg] dnsresolve ::1
> [9E131F8D:00000000 2017.11.30 12:06:57.141 dbg] dnsresolve ret
> Listening for requests on http://[::1]:8080/
> [9E131F8D:00000000 2017.11.30 12:06:57.142 dbg] dnsresolve 127.0.0.1
> [9E131F8D:00000000 2017.11.30 12:06:57.142 dbg] dnsresolve ret
> Listening for requests on http://127.0.0.1:8080/
> Please open http://127.0.0.1:8080/ in your browser.
> ************ Current Time : 2017-Nov-30 15:06:57.1421318 ************
> [9E131F8D:00000000 2017.11.30 12:06:57.142 dia] Running event loop...
> [9E131F8D:00000000 2017.11.30 12:06:57.142 trc] setup signal handler
> [9E131F8D:00000000 2017.11.30 12:06:57.142 dbg] Starting event loop.
> [9E131F8D:00000000 2017.11.30 12:06:57.142 dbv] Creating new fiber...

**Comment by tchaloupka** [comment]
Thats because Clock.currTime without specifiing also the time zone returns local time and vibe-d uses the UTC for the logged time. So the time is the same but just represented with 2 different timezones.

**Comment by s-ludwig** [comment]
Should be noted that using `Clock.currTime(UTC())` has the advantage of avoiding a number of time consuming conversion steps and of course it stays comparable between machines configured wth different time zones.

**Comment by zafer06** [comment]
Thanks for reply. I decided to swicth UTC and my problem is solve.
