### ISSUE TITLE
JSON parser must not accept trailing commas

### ISSUE THREAD

**Issue by s-ludwig** [vibe-d/vibe.d#1994]
Currently arrays and objects can end with a comma before the closing clamp, which is not allowed according to the JSON spec.

**Comment by wilzbach** [comment]
FWIW JSON5 (aka JSON for humans) allows this

**Comment by s-ludwig** [comment]
That would be one of the lenient modes that were sugessted from time to time, but that should be supported properly and officially instead of by accident. It turned out that a while ago only the serialization parser got fixed and the plain `parseJson` still had this issue.

**Comment by timotheecour** [comment]
Ya I'd really want to be able to keep current leniant behavior (at least as an option). Also, it could break a bunch of code if this were removed (eg, dub.json with trailing commas)

**Comment by quickfur** [comment]
It's probably wiser to be lenient when accepting incoming JSON (i.e., allow trailing commas), but strict when outputting JSON (never emit trailing commas).

**Comment by s-ludwig** [comment]
The problem with lenient behavior is that it doesn't protect users from writing invalid JSON. This is exactly what probably happened for DUB and now we likely have a bunch of non-conforant dub.json files flying around. What DUB should have done a long time ago is to start emitting warnings for trailing commas, so that at some point the behavior can be changed to strict.

**Comment by Geod24** [comment]
For reference `std.json` accepts trailing commas as of 2.088.0: https://github.com/dlang/phobos/pull/7074

**Comment by Geod24** [comment]
I'm going to close this because:
- Everyone else but OP would like to keep allowing trailing commas;
- A web framework should follow [Postel's Law](https://en.wikipedia.org/wiki/Robustness_principle);
- It would be a breaking change that we wouldn't be able to deprecate easily;

If you disagree @s-ludwig , feel free to comment / re-open.
