### ISSUE TITLE
[dox] Broken link to DictionaryList!...

### ISSUE THREAD

**Issue by quickfur** [vibe-d/vibe.d#1995]
In http://vibed.org/api/vibe.http.server/HTTPServerRequest under the `context` field, the type shows up as `vibe.utils.dictionarylist.__T14DictionaryListTS3std7variant18__T8VariantNVmi32Z8VariantNVbi1Vmi2Vbi0Z.DictionaryList` with a broken link.  Looks like somewhere along the line the doc generator got confused by the templated type and fails to generate the correct link?  Ideally, it should link to http://vibed.org/api/vibe.utils.dictionarylist/DictionaryList somehow so that someone reading the docs can find the type easily.

**Comment by quickfur** [comment]
@wilzbach Should this be moved to the vibed.org project too?

**Comment by wilzbach** [comment]
Documentation engine is here: https://github.com/rejectedsoftware/ddox

**Comment by quickfur** [comment]
Moved, thanks!
