### ISSUE TITLE
[dox][trivial] missing spaces around hyperlinks

### ISSUE THREAD

**Issue by quickfur** [vibe-d/vibe.d#1996]
In the section under http://vibed.org/docs#dub-publishing, several of the hyperlinks are missing spaces around them, causing the link text to clash with adjacent words.  E.g., the first link "DUB registry", then further down "code.dlang.org", then "git tag", etc..

**Comment by wilzbach** [comment]
Wrong repo -> https://github.com/vibe-d/vibed.org

**Comment by quickfur** [comment]
Moved, thanks!
