### ISSUE TITLE
dub init webchat -t vibe.d

### ISSUE THREAD

**Issue by EmTee70** [vibe-d/vibe.d#2024]
When trying to build a minimal vibe.d app with dub, version 0.7.32 is used 
resulting in a lot of deprecation warning. 
(dub version is: 1.6.0 from the apt repository, which is from Nov 1. so this is logical) but not very nice for people trying to learn and getting a lot of error like messages.

On my system I additionally had to add  
     ```versions "VibeNoSSL" ```
to get it compiled. Any hint for this?.

**Comment by wilzbach** [comment]
> On my system I additionally had to add versions "VibeNoSSL" to get it compiled. Any hint for this?.

This should really be automatically detected by DUB.
If you don't want to modify the `dub.sdl`, you can use 

```
dub --override-config="vibe-d:tls/openssl-1.1"
```

> When trying to build a minimal vibe.d app with dub, version 0.7.32 is used
resulting in a lot of deprecation warning.

What kind of deprecation warnings?
FWIW if you use an _old_ version of Vibe.d with the newest compiler, that's kinda expected. Use latest if you don't want to see deprecation warnings ;-)

**Comment by thaven** [comment]
> Use latest if you don't want to see deprecation warnings ;-)
But apparently, dub is not selecting the latest version in this case. Why?

**Comment by EmTee70** [comment]
> But apparently, dub is not selecting the latest version in this case. Why?

Yes, that is the point! 

It would be cool if there would be an automated tutorial tester, showing if documentation has to be changed ;-) starting with http://vibed.org/docs

**Comment by wilzbach** [comment]
> Yes, that is the point!

Ah I see - sorry. The fix for your issue is: https://github.com/dlang/dub/pull/1326
Though obviously it would be cool to automatically test such things or redesign them, s.t. these things can't happen.

**Comment by EmTee70** [comment]
!Offtopic! - but important - forum.dlang.org is down!

**Comment by Geod24** [comment]
This is really a dub issue and has been fixed (except for the Vibe.d SSL detection, fixed as well)
