### ISSUE TITLE
Detect OpenSSL 1.1 automatically

### ISSUE THREAD

**Issue by wilzbach** [vibe-d/vibe.d#2053]
Using

```
--override-config="vibe-d:tls/openssl-1.1"
```

all the time becomes a bit annoying and it's also very hard for newcomers to know that this option is needed when they look at the linker failures.

Ideas:

1) Dynamically load OpenSSL (dlang-requests does this: https://github.com/ikod/dlang-requests/issues/45)
2) Add a pregenerate script that detects the currently installed version, e.g. (`openssl version | cut -d " " -f2`)
3) Add such detection support in DUB, e.g. DUB will detect the versions of the libraries included for linking and then set special versions 

(1) will be a lot of work, (2) would be hard to get working in a cross-platform way and (3) will be quite spammy.

Anyhow I guess (2) is probably the least amount of work. Ideas?

**Comment by EmTee70** [comment]
I found the following - for me - strange behavior:
When using version "VibeNoSSL" and compiling with dub using dmd it compiles
and links.

When changing to the compiler to latest 1.7.0 ldc2 by --compiler ldc2

I get the openssl - probably known - linking errors: 
penssl.d:722: error: undefined reference to 'get_rfc3526_prime_2048'
openssl.d:911: error: undefined reference to 'SSL_load_error_strings'
openssl.d:912: error: undefined reference to 'SSL_library_init'
openssl.d:914: error: undefined reference to 'CRYPTO_num_locks'
openssl.d:922: error: undefined reference to 'CRYPTO_set_id_callback'
openssl.d:923: error: undefined reference to 'CRYPTO_set_locking_callback'
openssl.d:928: error: undefined reference to 'SSL_get_ex_new_index'
/home/mt/d/db-browse/../../.dub/packages/openssl-1.1.6_1.0.1g/openssl/deimos/openssl/safestack.d:140: error: undefined reference to 'sk_num'
/home/mt/d/db-browse/../../.dub/packages/openssl-1.1.6_1.0.1g/openssl/deimos/openssl/safestack.d:142: error: undefined reference to 'sk_value'
collect2: error: ld returned 1 exit status

which I could avoid using an additional --override-config="vibe-d:tls/openssl-1.1"

Do you know why?

**Comment by wilzbach** [comment]
Maybe with Vibe.d 0.8.4 OpenSSL 1.1 could be the new default?

**Comment by claudiocabral** [comment]
@EmTee70 I got it to compile in `ldc` with version `VibeNoSSL` adding 
```json
subConfiguration: {
    "vibe-d:tls": "notls"
}
```
I also noticed that if you don't pass this subconfiguration, `dmd` compiles because it links against openssl1.1.

I would expect `VersionNoSSL` to not use ssl at all, which is what I need for my project.

This build system needs to change a bit, I compile in macOS and Arch Linux and it's been quite annoying to find a configuration that works in both (macOS needs to link against openssl2.0 if memory doens't fail me)

**Comment by wilzbach** [comment]
A hack to detect OpenSSL 1.1 automatically: https://github.com/vibe-d/vibe.d/pull/2190
