### ISSUE TITLE
/vibe-d/utils/vibe/utils/array.d(326,19): Deprecation: The delete keyword has been deprecated.  Use object.destroy() instead.

### ISSUE THREAD

**Issue by timotheecour** [vibe-d/vibe.d#2075]
/Users/timothee/git_clone/D/vibe.d/utils/vibe/utils/array.d(326,19): Deprecation: The delete keyword has been deprecated.  Use object.destroy() instead.
/Users/timothee/git_clone/D/vibe.d/stream/vibe/stream/operations.d(466,45): Deprecation: The delete keyword has been deprecated.  Use object.destroy() instead.

**Comment by Geod24** [comment]
Fixed by https://github.com/vibe-d/vibe.d/pull/2102
