### ISSUE TITLE
Error: function vibe.http.server.HTTPServerRequest.path() is not callable using argument types (string)

### ISSUE THREAD

**Issue by timotheecour** [vibe-d/vibe.d#2076]
this used to compile in 0.7.x
```
void foo(string path, string relpath, scope HTTPServerRequest req, scope HTTPServerResponse res) {
  req.path = path;
  ...
}
```
what's a good replacement?

**Comment by wilzbach** [comment]
What's your use case for overwriting `req.path`? It's a readonly
(though yes, the API wasn't readonly in 0.7x)

**Comment by timotheecour** [comment]
is it `req.requestPath = path.Path;` ?

> What's your use case for overwriting req.path? It's a readonly

here:
```
void serve(string path, string relativepath, scope HTTPServerRequest req, scope HTTPServerResponse res) {
  req.requestPath = path.Path; // is it correct?
  auto file=relativepath.buildPath(path);
  auto lambda = serveStaticFiles(relativepath);
  lambda(req, res);
}
```

**Comment by Geod24** [comment]
If you need to override any request parameter, I would recommend to do it explicitly, by isolating the fields as its own parameter to the function / dg you are calling. Closing as the issue is quite outdated and restoring the old behavior now doesn't make sense.
