### ISSUE TITLE
Vibe.d webpage "Documentaion" has a broken link

### ISSUE THREAD

**Issue by RobT2012** [vibe-d/vibe.d#2084]
Under heading "First steps", the link as shown inside the quoted text gives a 404 error.

> First install the [DUB package manager](https://github.com/vibe-d/dub/) to let it handle downloading and building of vibe.d and derived applications. 

The link probably should be this https://code.dlang.org/download

**Comment by AlQurashi** [comment]
Shouldn't this issue be on the [Vibed.org](https://github.com/vibe-d/vibed.org) repo?

**Comment by s-ludwig** [comment]
Fixed by https://github.com/vibe-d/vibed.org/pull/51 - thanks @AlQurashi 

I'll also rephrase the paragraph a bit, since DUB is included with the compiler nowadays.
