### ISSUE TITLE
Ddoc parser complains: comment isn't matches to function declaration

### ISSUE THREAD

**Issue by denizzzka** [vibe-d/vibe.d#2094]
```
../../../.dub/packages/vibe-d-0.8.3-beta.1/vibe-d/utils/vibe/internal/meta/funcattr.d(100,16): Warning: Ddoc: function declaration has no parameter 'Hook'
../../../.dub/packages/vibe-d-0.8.3-beta.1/vibe-d/utils/vibe/internal/meta/funcattr.d(100,16): Warning: Ddoc: parameter count mismatch
```

**Comment by denizzzka** [comment]
#2094 isn't fixes this issue.
Probably, ddoc parser thinks that template args should be described by other way.

May be it is dmd issue?

**Comment by s-ludwig** [comment]
Oh, didn't notice that it was a template parameter. I'm not sure if DMD complains there also, but in Phobos I found many places where the template is separated from the function like this:
```
/** ...

    Params:
        fun = doc of fun
        range = doc of range
*/
template map(fun...) {
    auto map(R)(R range)
    { ... }
}
```

Considering that this is used throughout Phobos, it seems like indeed DMD should also accept the syntax in #2098 without warnings. I also thought that I had seen something like a "Template_Params:" section, but I can't find it now, and it's also not mentioned in the specification.

**Comment by denizzzka** [comment]
Isn't reproduceable, can be closed
