### ISSUE TITLE
StdinStream not behaving as expected

### ISSUE THREAD

**Issue by Herringway** [vibe-d/vibe.d#2103]
Since the switch to vibe-core, this code does not behave as expected:
```D
#!/usr/bin/env dub
/+ dub.json:
{
	"dependencies": {
		"vibe-d:core": "0.8.3-rc.1",
		"vibe-d:stream": "0.8.3-rc.1"
	}
}
+/
import vibe.core.core;
import vibe.core.stream;
import vibe.stream.operations;
import vibe.stream.stdio;
import std.stdio;

void main() {
	void runUI() {
		auto standardInput = new StdinStream;
		while (true) {
			auto str = cast(string)readLine(standardInput);
			writeln(str);
			if (str == "exit") {
				exitEventLoop();
			}
		}
	}
	runTask(&runUI);
	runApplication();
}
```

**Expected**: User inputs line of text, text is echoed back (unless it's exit, then the program closes).

**Actual**: User inputs line of text, nothing happens. User can no longer input any text. Ctrl+c does not end the program, but keeps it running in the background.

**OS**: Windows 10 v1709, x86-64 with DMD 2.079.0.

Behaves nearly identically on an up-to-date Arch Linux install, except ctrl+c does end the program as expected.

**Comment by s-ludwig** [comment]
Tagged a new vibe-core release that should resolve this (behaves the same for libevent and vibe-core now for me). There is still the issue that the internal thread created for `StdinStream` stops the application from exiting at the end, unless it is closed explicitly, but that is an issue that has always been there AFICT.

Can you verify with upgraded dependencies?

**Comment by Herringway** [comment]
Yep, can confirm the fixes on windows and linux, though I only just noticed that StdinStream defaults to \r\n on linux, whoops.

Thanks for the fix!

I'll leave this open for the last remaining issue.

**Comment by s-ludwig** [comment]
That's actually the default of the `readLine` function. You can call it with `readLine(standardInput, size_t.max, "\n")` to assume Unix line breaks. It shows that this was implemented in the context of the HTTP implementation where line breaks are defined as `\r\n` and really is not ideal overall.

I'd close the ticket here, though, and open a new one for the shutdown issue.
