### ISSUE TITLE
Websockets not connected initially

### ISSUE THREAD

**Issue by OlaOst** [vibe-d/vibe.d#2104]
Using vibe-d-0.8.3-rc.1 and DMD v2.078.3.

When running the websocket example with dub --arch=x86_64, websockets have the connected property set to false initially in handleWebSocketConnection.

Websockets are connected initially in vibe-d-0.8.2-rc.1

**Comment by s-ludwig** [comment]
Just to verify, did this (only) occur on Windows or (also) on other systems?

**Comment by OlaOst** [comment]
This is on Windows 10, 64 bit.

I haven't tested on other systems.

**Comment by s-ludwig** [comment]
Okay, should be fixed with a "dub upgrade". The actual fix is in vibe-d/eventcore#55.

**Comment by OlaOst** [comment]
That fixed it!

Thanks for the quick response :)
