### ISSUE TITLE
[Vibe 0.8.3] StreamOutputRange dosn't work with new ProxyStream

### ISSUE THREAD

**Issue by rracariu** [vibe-d/vibe.d#2116]
In 0.8.2 this used to work:

`StreamOutputRange(res.bodyWriter)`

with 0.8.3 `bodyWriter` returns an `InterfaceProxy!OutputStream` which fails to validate as `OutputStream` in the ranges's constraints.

**Comment by s-ludwig** [comment]
The problem is that parameter type inference doesn't work for constructors. There is a free function [`streamOutputRange`](http://vibed.org/api/vibe.stream.wrapper/streamOutputRange) that should be used instead.

**Comment by rracariu** [comment]
OK, the function works, thanks!
