### ISSUE TITLE
Vibe should exit when there are no more registered events

### ISSUE THREAD

**Issue by CyberShadow** [vibe-d/vibe.d#212]
One tell of a good asynchronous library is that the program will automatically exit when there is no more work to do. That is, the program may start up a few parallel HTTP requests, and exit once the last one was completed and processed. An HTTP server should quit by closing its listening socket; then, the program would exit after the last client HTTP connection was closed.

I noticed that Vibe instead determines when to exit by checking a flag in its event loop. I believe this approach is not ideal, as it will result in tasks terminating abruptly while waiting for an asynchronous operation to complete. In my `ae` library, I have instead implemented a centralized shutdown notification system (triggered by a signal / Ctrl+C, or from user code), which allows components to close listening ports, gracefully close long-running connections, stop timers, and perform a clean exit after completing all in-progress tasks.

Initially, I thought that Vibe's current behavior - to keep running, and waiting indefinitely for 0 events - was a defect in the libevent driver, however the same problem occurs with the win32 driver. It seems to be by design.

**Comment by Geod24** [comment]
AFAICS, this has been fixed (feel free to comment / re-open if that's not the case).
