### ISSUE TITLE
Win32 linker issues with OpenSSL (and TLS in general)

### ISSUE THREAD

**Issue by punkUser** [vibe-d/vibe.d#2122]
Hey guys I've recently updated to the Vibe 0.8.3 and DMD 2.079.0 and I'm now running into a bunch of linker issues with Vibe.d that reproduce even in the test application:

```
OPTLINK (R) for Win32  Release 8.00.17
Copyright (C) Digital Mars 1989-2013  All rights reserved.
http://www.digitalmars.com/ctg/optlink.html
[path].dub\lib\vibe-d_tls.lib(openssl) 
 Error 42: Symbol Undefined _BIO_new
[path].dub\lib\vibe-d_tls.lib(openssl) 
 Error 42: Symbol Undefined _SSL_set_bio
[path].dub\lib\vibe-d_tls.lib(openssl) 
 Error 42: Symbol Undefined _SSL_set_ex_data
... lots more ...
[path].dub\lib\vibe-d_tls.lib(openssl) 
 Error 42: Symbol Undefined _sk_num
[path].dub\lib\vibe-d_tls.lib(openssl) 
 Error 42: Symbol Undefined _sk_value
```

Naively it seems like they might be vaguely related to #2053, but in this case adding "--override-config="vibe-d:tls/openssl-1.1" actually does *not* fix the issue, nor does any other OpenSSL versions or even botan. They all just have different missing linker symbols, but none work.

The only workaround I've found is adding "VibeNoSSL" to versions, which allows it to link and run again on Windows (although obvious with no TLS support). Strangely, even with that version tag it still gets the above linker errors if you try to compile it in Visual Studio using VisualD and a project generated by dub (I think due to "Have_openssl" still being defined in versions for the tls project, but not sure).

I'm a bit stuck on what to do to debug further given that this happens with any vibe project on the latest release. I was a bit surprised to not find an issue here already given that, so if there is already one filed feel free to merge/link this one.

Thanks!

**Comment by s-ludwig** [comment]
This is caused by a DUB regression in 1.8.0 that unfortunately went undiscovered in the beta phase: https://github.com/dlang/dub/pull/1409

The easiest workaround would be to install 1.7.2 in the [standalone version](http://code.dlang.org/files/dub-1.7.2-setup.exe), or to roll back to DMD 2.078.3.

**Comment by punkUser** [comment]
Ah thanks for the pointer, I should have thought to check dub's issue tracker as well, just got off in the weeds with the OpenSSL changes in vibe. Will downgrade dub for now, thanks!

**Comment by Aphexus** [comment]
This does not work for me, downgraded to dub 1.7.2 and same errors(same missing symbols at least). Why isn't the project testing on a fresh install when releasing significant changes? It seems that this would be very easy to setup and automate to make sure that you don't cause a lot of people grief for no reason.

**Comment by bubnenkoff** [comment]
Same issue. I can't even get work OpenSSL 1.0

Windows 10
DMD32 D Compiler v2.084.0

I tried different combinations of vibed 0.8.4 and openSSL 1.0/1.1 -- without result. 

Any hacks from here and related topics did not get any affect. 

https://forum.dlang.org/thread/uaprrobsefqhaqahcthu@forum.dlang.org

**Comment by bubnenkoff** [comment]
I got it's compile with adding to dub.sdl next string:
`"dflags-windows-x86": ["-m32mscoff"]`
