### ISSUE TITLE
[Jenkins] Vibe.d+libevent-base segfaults with latest DMD

### ISSUE THREAD

**Issue by wilzbach** [vibe-d/vibe.d#2157]
Example: https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fdmd/detail/PR-8223/14/pipeline/

```
+ dub build --combined --arch=x86 --config=libevent
Performing "debug" build using /var/lib/jenkins/dlang_projects@4/distribution/bin/dmd for x86.
vibe-d 0.8.3: building configuration "libevent"...
```

Currently I don't have the time to dig into this one, so putting it here & temporarily disabling the test from the project tester :/

**Comment by s-ludwig** [comment]
Shouldn't this be on the DMD bug tracker instead? This is a segfault in the compiler after all.

**Comment by wilzbach** [comment]
This has been fixed a while ago.
