### ISSUE TITLE
HTTPClientResponse - InvalidMemoryOperationError

### ISSUE THREAD

**Issue by BenjaminSchaaf** [vibe-d/vibe.d#2178]
This is more of a general issue I encountered when specifically dealing with a `HTTPClientResponse`. I was using the overload of `requestHTTP` that returns the client response, meaning that response has a [LockedConnection!HTTPClient](https://github.com/vibe-d/vibe.d/blob/03b85894ff8e88f3f92001c0750f809aa3ccb1f8/http/vibe/http/client.d#L886) set. `LockedConnection` rightfully [has a destructor with some asserts](https://github.com/vibe-d/vibe.d/blob/03b85894ff8e88f3f92001c0750f809aa3ccb1f8/core/vibe/core/connectionpool.d#L140). I wasn't handling the client response properly so once the GC showed its head once of those asserts failed. But instead of being treated with a nice "Locked connection destroyed in foreign task." assertion error, because asserts allocate memory I got a `InvalidMemoryOperationError` without a stacktrace instead.

For my case the workaround is to use the safer `requestHTTP` overload, but there are other cases where a possibly allocating method is called in a class destructor:
https://github.com/vibe-d/vibe.d/blob/03b85894ff8e88f3f92001c0750f809aa3ccb1f8/http/vibe/http/client.d#L965
https://github.com/vibe-d/vibe.d/blob/03b85894ff8e88f3f92001c0750f809aa3ccb1f8/core/vibe/core/drivers/libasync.d#L516
etc...

While [this is certainly debuggable](https://wiki.dlang.org/InvalidMemoryOperationError) I think a more friendly approach can/should be taken to make these sorts of bugs easier to deal with.

**Comment by Geod24** [comment]
[The upstream issues ](https://issues.dlang.org/show_bug.cgi?id=7349) was fixed in v2.097.0.
