### ISSUE TITLE
Missing O_CLOEXEC for Solaris

### ISSUE THREAD

**Issue by fantassin** [vibe-d/vibe.d#2196]
in eventcore/sockets.d       

 static if (!is(typeof(O_CLOEXEC)))
        {
                version (linux) enum O_CLOEXEC = 0x80000;
                else version (FreeBSD) enum O_CLOEXEC = 0x100000;
                else version (Solaris) enum O_CLOEXEC = 0x800000; // line missing
                else version (DragonFlyBSD) enum O_CLOEXEC = 0x0020000;
                else version (NetBSD) enum O_CLOEXEC = 0x400000;
                else version (OpenBSD) enum O_CLOEXEC = 0x10000;
                else version (OSX) enum O_CLOEXEC = 0x1000000;
        }

**Comment by wilzbach** [comment]
For reference, the eventcore package is here:

https://github.com/vibe-d/eventcore

I moved the issue your issue to the repository.
