### ISSUE TITLE
autogenerated RestInterface to consume whole json body as struct

### ISSUE THREAD

**Issue by vitalka200** [vibe-d/vibe.d#2198]
I'm porting some existing java+spring service into vibe.d, 
and I can't find any documentation on how to achieve the following with autogenerated RestInterface

Here is the simplified rest request that I want to consume on vibe.d backend side

**Request**
```
POST /some/param1/path/param2/hello

{
  "field1": val1,
  "field2": val2,
  "field3": {
      "inner1": innerval1,
      ....
  }
  ....
  "fieldN": valN
}
```
**Reply**
```
{
  "field1": val1,
  ...
  "fieldN":valN
}
```

Where `N > 15` and path parameters `param1` and `param2` are dynamic path parameters.

In Spring It look like following:
```java
class Controller {
    @RequestMapping("/some/{param1}/path/{param2}/hello")
    public ReplyObject hello(@PathVariable String param1, 
                             @PathVariable param2, 
                             @RequestBody RequestObject reqObj) {
        return new ReplyObject();
    }
}
class ReplyObject {}
class RequestObject {
    string field1;
    string field2;
    NestedObject field3;
    ....
    string fieldN;
}
```

`@RequestBody` means that whole json request body would be deserialised into `RequestObject` object

So in vibe.d I found all the UDAs that analogous to Spring's
`@RequestMapping` -> `@path + @method`
`@PathVariable` -> `naming convention of using '_' before variable name` (is there any UDA in addition to convention it would be really great for readability)

```D
interface IRest {
    @method(HTTPMethod.POST)
    @path("/some/:param1/path/:param2/hello")
    ReplyObject hello(string _param1, string _param2, RequestObject reqObj);
}
```

I saw that I could use `@property` but it's limited to `PUT`, single parameter and `void` as return type.

I can't find the one for `@RequestBody`, is it even exist?
Is such scenario supported in autogenerated `RestInterface`?

**Comment by Geod24** [comment]
There's an UDA for it, it's `@bodyParam("param_name", "object name")`.
See "Parameter passing" in http://vibed.org/api/vibe.web.rest/

**Comment by vitalka200** [comment]
The problem with @bodyParam is it need a param_name and then it’s works. What I need is to deserialize the **whole** body as struct and **not only** specific param inside the json body

**Comment by Geod24** [comment]
If you don't provide a field name it will take the whole body.

**Comment by vitalka200** [comment]
Thank you!
Is there a way this behaviour can be documented?
