### ISSUE TITLE
connectMongoDB crash

### ISSUE THREAD

**Issue by Ivo-Maffei** [vibe-d/vibe.d#2207]
My application contains the following function
```D
void connect (const string host, const string user , const string password ) {
		writeln("################# connecting to MongoDB");
		_mongoClient = connectMongoDB("mongodb://"~ user ~":"~ password~ "@" ~host ~ "/officeManager?authMechanism=SCRAM-SHA-1");
		writeln("################# connected client");
		_host = host;
		writeln("################ connection done");
	}
```

and the program crashes when calling `connectMongoDB` while no MongoDB instance is running.

I would like an exception to be thrown or the chance to set a timeout

**Comment by s-ludwig** [comment]
What kind of crash did you get? I get an exception, as expected: https://run.dlang.io/is/OrUViM

It will, however crash the application through an assertion failure if the exception occurs inside of a task and doesn't get caught. Wrapping the task function in a `try {} catch {}` should fix it in that case.

**Comment by Geod24** [comment]
Closing as the likely cause for this was the uncaught Exception. Good those are deprecated!
