### ISSUE TITLE
Error: linker exited with status 1

### ISSUE THREAD

**Issue by Beyarz** [vibe-d/vibe.d#2217]
(dmd-2.082.0)┌─[bn@algonquians]─[~/Desktop/portfolio-master]$ dub
Fetching libevent 2.0.2+2.0.16 (getting selected version)...
Fetching diet-ng 1.5.0 (getting selected version)...
Fetching taggedalgebraic 0.10.11 (getting selected version)...
Fetching openssl 1.1.6+1.0.1g (getting selected version)...
Fetching botan 1.12.10 (getting selected version)...
Fetching stdx-allocator 2.77.4 (getting selected version)...
Fetching vibe-d 0.8.4 (getting selected version)...
Fetching mir-linux-kernel 1.0.1 (getting selected version)...
Fetching vibe-core 1.4.3 (getting selected version)...
Fetching libasync 0.8.3 (getting selected version)...
Fetching memutils 0.4.12 (getting selected version)...
Fetching botan-math 1.0.3 (getting selected version)...
Fetching eventcore 0.8.36 (getting selected version)...
Performing "debug" build using /home/bn/dlang/dmd-2.082.0/linux/bin64/dmd for x86_64.
taggedalgebraic 0.10.11: building configuration "library"...
eventcore 0.8.36: building configuration "epoll"...
stdx-allocator 2.77.4: building configuration "library"...
vibe-core 1.4.3: building configuration "epoll"...
../../.dub/packages/vibe-core-1.4.3/vibe-core/source/vibe/core/core.d(692,70): Deprecation: std.algorithm.setops.No is not visible from module core
../../.dub/packages/vibe-core-1.4.3/vibe-core/source/vibe/core/log.d(33,23): Deprecation: opDot is deprecated. Use alias this
../../.dub/packages/vibe-core-1.4.3/vibe-core/source/vibe/core/log.d(50,3): Deprecation: opDot is deprecated. Use alias this
../../.dub/packages/vibe-core-1.4.3/vibe-core/source/vibe/core/log.d(51,3): Deprecation: opDot is deprecated. Use alias this
../../.dub/packages/vibe-core-1.4.3/vibe-core/source/vibe/core/log.d(67,3): Deprecation: opDot is deprecated. Use alias this
../../.dub/packages/vibe-core-1.4.3/vibe-core/source/vibe/core/log.d(68,3): Deprecation: opDot is deprecated. Use alias this
../../.dub/packages/vibe-core-1.4.3/vibe-core/source/vibe/core/log.d(847,14): Deprecation: opDot is deprecated. Use alias this
../../.dub/packages/vibe-core-1.4.3/vibe-core/source/vibe/core/log.d(852,9): Deprecation: opDot is deprecated. Use alias this
../../.dub/packages/vibe-core-1.4.3/vibe-core/source/vibe/core/log.d(860,13): Deprecation: opDot is deprecated. Use alias this
../../.dub/packages/vibe-core-1.4.3/vibe-core/source/vibe/core/log.d(861,10): Deprecation: opDot is deprecated. Use alias this
../../.dub/packages/vibe-core-1.4.3/vibe-core/source/vibe/core/log.d(865,10): Deprecation: opDot is deprecated. Use alias this
../../.dub/packages/vibe-core-1.4.3/vibe-core/source/vibe/core/log.d(869,11): Deprecation: opDot is deprecated. Use alias this
../../.dub/packages/vibe-core-1.4.3/vibe-core/source/vibe/core/log.d(870,11): Deprecation: opDot is deprecated. Use alias this
../../.dub/packages/vibe-core-1.4.3/vibe-core/source/vibe/core/log.d(871,11): Deprecation: opDot is deprecated. Use alias this
vibe-d:utils 0.8.4: building configuration "library"...
vibe-d:data 0.8.4: building configuration "library"...
mir-linux-kernel 1.0.1: building configuration "library"...
vibe-d:crypto 0.8.4: building configuration "library"...
diet-ng 1.5.0: building configuration "library"...
vibe-d:stream 0.8.4: building configuration "library"...
vibe-d:textfilter 0.8.4: building configuration "library"...
vibe-d:inet 0.8.4: building configuration "library"...
vibe-d:tls 0.8.4: building configuration "openssl"...
vibe-d:http 0.8.4: building configuration "library"...
vibe-d:mail 0.8.4: building configuration "library"...
vibe-d:mongodb 0.8.4: building configuration "library"...
../../.dub/packages/vibe-d-0.8.4/vibe-d/mongodb/vibe/db/mongo/settings.d(16,8): Deprecation: alias `std.digest.digest.toHexString` is deprecated - import std.digest instead of std.digest.digest. std.digest.digest will be removed in 2.084
../../.dub/packages/vibe-d-0.8.4/vibe-d/mongodb/vibe/db/mongo/settings.d(16,8): Deprecation: alias `std.digest.digest.toHexString` is deprecated - import std.digest instead of std.digest.digest. std.digest.digest will be removed in 2.084
vibe-d:redis 0.8.4: building configuration "library"...
vibe-d:web 0.8.4: building configuration "library"...
vibe-d 0.8.4: building configuration "vibe-core"...
portfolio ~master: building configuration "application"...
Compiling Diet HTML template index.dt...
Linking...
/usr/bin/ld: ../../.dub/packages/vibe-d-0.8.4/vibe-d/tls/.dub/build/openssl-debug-linux.posix-x86_64-dmd_2082-5A0C6DB8276F47E3C5101A5F680943D9/libvibe-d_tls.a(openssl_fa_569.o): in function `_D4vibe6stream7openssl14OpenSSLContext6__ctorMFNfEQBwQBu3tls14TLSContextKindEQCxQCvQBb10TLSVersionZ9__lambda3MFNbNeZv':
/home/bn/Desktop/portfolio-master/../../.dub/packages/vibe-d-0.8.4/vibe-d/tls/vibe/stream/openssl.d:470: undefined reference to `SSLv23_client_method'
/usr/bin/ld: /home/bn/Desktop/portfolio-master/../../.dub/packages/vibe-d-0.8.4/vibe-d/tls/vibe/stream/openssl.d:471: undefined reference to `SSLv23_client_method'
/usr/bin/ld: /home/bn/Desktop/portfolio-master/../../.dub/packages/vibe-d-0.8.4/vibe-d/tls/vibe/stream/openssl.d:475: undefined reference to `SSLv23_client_method'
/usr/bin/ld: /home/bn/Desktop/portfolio-master/../../.dub/packages/vibe-d-0.8.4/vibe-d/tls/vibe/stream/openssl.d:476: undefined reference to `SSLv23_client_method'
/usr/bin/ld: /home/bn/Desktop/portfolio-master/../../.dub/packages/vibe-d-0.8.4/vibe-d/tls/vibe/stream/openssl.d:483: undefined reference to `SSLv23_server_method'
/usr/bin/ld: /home/bn/Desktop/portfolio-master/../../.dub/packages/vibe-d-0.8.4/vibe-d/tls/vibe/stream/openssl.d:484: undefined reference to `SSLv23_server_method'
/usr/bin/ld: /home/bn/Desktop/portfolio-master/../../.dub/packages/vibe-d-0.8.4/vibe-d/tls/vibe/stream/openssl.d:486: undefined reference to `SSLv23_server_method'
/usr/bin/ld: /home/bn/Desktop/portfolio-master/../../.dub/packages/vibe-d-0.8.4/vibe-d/tls/vibe/stream/openssl.d:487: undefined reference to `SSLv23_server_method'
/usr/bin/ld: ../../.dub/packages/vibe-d-0.8.4/vibe-d/tls/.dub/build/openssl-debug-linux.posix-x86_64-dmd_2082-5A0C6DB8276F47E3C5101A5F680943D9/libvibe-d_tls.a(openssl_fa_569.o): in function `_D4vibe6stream7openssl14OpenSSLContext11setDHParamsMFNeAyaZv':
/home/bn/Desktop/portfolio-master/../../.dub/packages/vibe-d-0.8.4/vibe-d/tls/vibe/stream/openssl.d:725: undefined reference to `get_rfc3526_prime_2048'
/usr/bin/ld: ../../.dub/packages/vibe-d-0.8.4/vibe-d/tls/.dub/build/openssl-debug-linux.posix-x86_64-dmd_2082-5A0C6DB8276F47E3C5101A5F680943D9/libvibe-d_tls.a(safestack_5eb_449.o): in function `_D6deimos7openssl9safestack__T10SKM_sk_numTSQBqQBm6x509v315GENERAL_NAME_stZ__TQBwZQCaFNbPSQDkQDgQDb__T8STACK_OFTQCrZQoZi':
/home/bn/Desktop/portfolio-master/../../.dub/packages/openssl-1.1.6_1.0.1g/openssl/deimos/openssl/safestack.d:140: undefined reference to `sk_num'
/usr/bin/ld: ../../.dub/packages/vibe-d-0.8.4/vibe-d/tls/.dub/build/openssl-debug-linux.posix-x86_64-dmd_2082-5A0C6DB8276F47E3C5101A5F680943D9/libvibe-d_tls.a(safestack_5ed_516.o): in function `_D6deimos7openssl9safestack__T12SKM_sk_valueTSQBsQBo6x509v315GENERAL_NAME_stZ__TQByZQCcFNbPSQDmQDiQDd__T8STACK_OFTQCrZQoiZPQDa':
/home/bn/Desktop/portfolio-master/../../.dub/packages/openssl-1.1.6_1.0.1g/openssl/deimos/openssl/safestack.d:142: undefined reference to `sk_value'
/usr/bin/ld: ../../.dub/packages/vibe-d-0.8.4/vibe-d/tls/.dub/build/openssl-debug-linux.posix-x86_64-dmd_2082-5A0C6DB8276F47E3C5101A5F680943D9/libvibe-d_tls.a(openssl.o): in function `_D4vibe6stream7openssl25_sharedStaticCtor_L911_C1FZv':
/home/bn/Desktop/portfolio-master/../../.dub/packages/vibe-d-0.8.4/vibe-d/tls/vibe/stream/openssl.d:914: undefined reference to `SSL_load_error_strings'
/usr/bin/ld: /home/bn/Desktop/portfolio-master/../../.dub/packages/vibe-d-0.8.4/vibe-d/tls/vibe/stream/openssl.d:915: undefined reference to `SSL_library_init'
/usr/bin/ld: /home/bn/Desktop/portfolio-master/../../.dub/packages/vibe-d-0.8.4/vibe-d/tls/vibe/stream/openssl.d:917: undefined reference to `CRYPTO_num_locks'
/usr/bin/ld: /home/bn/Desktop/portfolio-master/../../.dub/packages/vibe-d-0.8.4/vibe-d/tls/vibe/stream/openssl.d:925: undefined reference to `CRYPTO_set_id_callback'
/usr/bin/ld: /home/bn/Desktop/portfolio-master/../../.dub/packages/vibe-d-0.8.4/vibe-d/tls/vibe/stream/openssl.d:926: undefined reference to `CRYPTO_set_locking_callback'
/usr/bin/ld: /home/bn/Desktop/portfolio-master/../../.dub/packages/vibe-d-0.8.4/vibe-d/tls/vibe/stream/openssl.d:931: undefined reference to `SSL_get_ex_new_index'
collect2: error: ld returned 1 exit status
Error: linker exited with status 1
/home/bn/dlang/dmd-2.082.0/linux/bin64/dmd failed with exit code 1.

**Comment by Beyarz** [comment]
Solved it by installing libssl1.0-dev.

**Comment by BoQsc** [comment]
Problem still exist.
And unable to achieve simple installation of **ibssl1.0-dev**
```
aidas@SATELLITE-L855:~$ sudo apt-get install libssl1.0-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libssl1.0-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libssl1.0-dev' has no installation candidate
```
