### ISSUE TITLE
Unable to serveRestJSClient with empty URL

### ISSUE THREAD

**Issue by deviator** [vibe-d/vibe.d#2222]
If I want to use js client generation I **must** to specify url for requests. But if I want use my program in different machines I need to get ip at each machine at start of program. If I want use many internet interfaces with different ip it's makes problems. But js client what send requests to self server don't need full url (for example `http://192.168.99.13/api/v1/some`). It's can send requests to relative url (`/api/v1/some`).

**Comment by Beyarz** [comment]
If you don't want to specify the ip addresses manually you can use [this](https://code.dlang.org/packages/my-ip?tab=info) package.

**Comment by deviator** [comment]
> If you don't want to specify the ip addresses manually you can use [this](https://code.dlang.org/packages/my-ip?tab=info) package.

I know, thanks, but problem is deeper: device with my program can be in local network with complicated structure (this is my real case) and determine ip address in other networks (where my device has remaped ip) can be problematic and can need more what one steps. And this problem will not appear if `serveRestJSClient` will can use empty url.
