### ISSUE TITLE
Dub takes a long time to link

### ISSUE THREAD

**Issue by Flatllin** [vibe-d/vibe.d#2225]
Whenever I run `dub run` in my vibe.d project, It takes ~10 seconds on the "linking..." phase. Is there a way to speed this step up? It is very time consuming to have to wait 10 seconds every time I build.

**Comment by wilzbach** [comment]
Have you tried using ld.gold?

**Comment by Flatllin** [comment]
@wilzbach what is ld.gold?

**Comment by wilzbach** [comment]
A better linker: https://code.dawg.eu/reducing-vibed-turnaround-time-part-1-faster-linking.html

**Comment by Flatllin** [comment]
Thanks so much! That made it WAAAAAAAAAAAY faster!
