### ISSUE TITLE
module constructor called again when reading request + readOption = request hangs

### ISSUE THREAD

**Issue by aliak00** [vibe-d/vibe.d#2262]
A requestHTTP seems to hang if I use a `readOption` in a module constructor, which seems to be called again when a request is handled. Here's a minimized sample:
```d

import vibe.vibe;
import std.stdio;

static this() {
    ushort port;
    writeln("reading port");
    readOption("p|port", &port, "help"); // comment this out and the request will go though
}

void main() {
    import vibe.d;
    auto settings = new HTTPServerSettings;
    settings.bindAddresses = ["0.0.0.0"];
    settings.port = 8080;
    listenHTTP(settings, (req, res) {
        auto response = requestHTTP("https://httpbin.org/get", (scope request) {
            request.method = HTTPMethod.GET;
        });

        // we never reach here
        writeln(response.bodyReader.readAllUTF8);

        res.writeBody("Hello, World: " ~ req.path);
    });
    runApplication();
}
```

I realize that `readOption` should only be called once, but why is the module constructor called again when a request is handled?

**Comment by Geod24** [comment]
Because you should use a shared module ctor (`shared static this`) over a module ctor (`static this`).

**Comment by aliak00** [comment]
Aha! Yes that worked :) Thank you!

But is it valid to say that `requestHTTP` should not hang if `readOption` is called twice?

**Comment by Geod24** [comment]
I think what happened (untested, but I draw from reading the code and past experience) is that you triggered this assert:
https://github.com/vibe-d/vibe.d/blob/03b85894ff8e88f3f92001c0750f809aa3ccb1f8/core/vibe/core/args.d#L56

And that killed the thread (because `AssertError` gets thrown from the module ctor), which somehow leaves `requestHTTP` hanging.

**Comment by aliak00** [comment]
Boh, I think you're right, and it seems D doesn't say anything if there's an assert error in a thread [0] :/ ah well.

Not sure what the correct behavior is here ... 

[0] https://forum.dlang.org/post/btzlsnrxncovzhgayocd@forum.dlang.org

**Comment by Geod24** [comment]
I think we can close this ?

**Comment by aliak00** [comment]
Sure! I believe non-shared module constructor is being (or has already been) deprecated as well anyway?
