### ISSUE TITLE
Calling sleep from idle handler causes vibed to reenter idle handler

### ISSUE THREAD

**Issue by Temtaime** [vibe-d/vibe.d#2272]
Set up idle handler with setIdleHandler, then try to call sleep within it.
Vibed will call idle handler once more(and more, if the sleep is unconditional) while old handler is still active.
Seems there's no way currently to disable this behavior.

**Comment by s-ludwig** [comment]
What is goal of waiting in the idle handler? It is called synchronously from the event loop, so no operations should be done that yield execution. Either you should start a new task and perform the sleep with the surrounding operations in there, or, if the goal is to slow down event processing in some way, use `Thread.sleep` instead.

**Comment by Temtaime** [comment]
Thanks for a reply.
I want to do some computations in background by executing external processes and waiting unless they're completed (for example by calling tryWait). So, while they're running, i want the app to respond to the requests.
What's the best way to achieve this then ? Wrap all the code in the idle handler in runTask ?

**Comment by s-ludwig** [comment]
Currently I'd recommend to execute the process in a separate thread and use message passing to communicate the process exit to the main thread. I have an old version of a similar approach as a gist: [PipedProcess](https://gist.github.com/s-ludwig/8434299)

At some point there should be first-class support for processes on vibe.d. @BenjaminSchaaf has just made a great first step with Linux support in eventcore (https://github.com/vibe-d/eventcore/pull/100) and I'll try to follow up with a Windows implementation, soon.

**Comment by Temtaime** [comment]
Thanks, got it.

**Comment by BenjaminSchaaf** [comment]
@s-ludwig Wasn't sure whether anyone has actually looked at that yet :) I've got an implementation for vibe-core waiting as well.

@Temtaime I've already written a package for handling processes using threads. It's pretty stable (currently using it in production): http://code.dlang.org/packages/supervised
