### ISSUE TITLE
Getting first file of request is complicated

### ISSUE THREAD

**Issue by andre2007** [vibe-d/vibe.d#2278]
After investigating the source code of dictionarylist.d, it seems this is the only way to get the first file of the  request.files property.

```d
import vibe.inet.webform : FilePart;

FilePart uploadedFile;
foreach (k, v; req.files.byKeyValue())
{
    uploadedFile = v;
    break;
}
```

Could you provide something simpler?

**Comment by s-ludwig** [comment]
You could also do `req.files.byValue.front`, if you know that there is at least one file. But wouldn't the usual way to query a single file be `req.files.get("field")` or `req.files["field"]`? Or do you explicitly want to accept any key to support arbitrary upload tools?

**Comment by andre2007** [comment]
Yes, in my case I just know a python application is sending 1 file using the library "requests"

```python
model_file_path='...'
files = {'file': open(model_file_path, 'rb')}
requests.post('http://127.0.0.1/compile', files=files)
```

How the file is actually called I do not know. ```req.files.byValue.front``` seems a good solution.
Thanks :)
