### ISSUE TITLE
IP binding doesn't seem reliable anymore on linux

### ISSUE THREAD

**Issue by WebFreak001** [vibe-d/vibe.d#2280]
I just upgraded to rc.1 but now my usual web service code which listens on IPv6 and IPv4 only _sometimes_ starts with listening on IPv6. I don't really know how to reproduce it, but I'm absolutely sure that there are no other apps listening on that port and that the app itself is also fully shutdown before starting again.

Code:
```sdl
name "hnsecs"

dependency "vibe-d" version="~>0.8.5-rc.1"
```

```d
import vibe.vibe;

void main(string[] args)
{
	auto settings = new HTTPServerSettings;
	settings.port = 2108;
	settings.bindAddresses = ["::1", "127.0.0.1"];

	auto router = new URLRouter();
	router.get("/js", serveStaticFile("public/a.js"));
	router.get("/css", serveStaticFile("public/b.css"));
	router.any("*", function(scope HTTPServerRequest req, scope HTTPServerResponse res) {
		res.writeBody(import("c.html").someTransform(), "text/html");
	});


	listenHTTP(settings, router);
	runApplication();
}
```

Apps listening on port when starting the app:
```
Netid  State   Recv-Q  Send-Q  Local Address:Port  Peer Address:Port
tcp    LISTEN  0       128     127.0.0.1:2108      0.0.0.0:*          users:(("hnsecs",pid=30182,fd=6))
```
note that there is no ipv6 listed here, just _sometimes_

It seems to break when the server was running, then accessed through nginx reverse proxy over ipv6 and then stopping and restarting the app. The app can be fully shutdown and `ss -tulpn` doesn't show any port usage but it still doesn't start ipv6 on next few starts then. (maybe some timeout)
```
Netid  State   Recv-Q  Send-Q  Local Address:Port  Peer Address:Port
tcp    LISTEN  0       128     127.0.0.1:2108      0.0.0.0:*          users:(("hnsecs",pid=1970,fd=7))
tcp    LISTEN  0       128     [::1]:2108          [::]:*             users:(("hnsecs",pid=1970,fd=6))
```

When an app is running with ipv6 it's running stable, but on restart it seems to fail a lot

**Comment by dd86k** [comment]
Try `["127.0.0.1", "::1"]` for fun

**Comment by WebFreak001** [comment]
sadly that didn't seem to work either

**Comment by gedaiu** [comment]
I have the same problem... is there a workaround for this?

**Comment by s-ludwig** [comment]
I didn't have the chance to take a closer look, but could this be the reason: https://github.com/vibe-d/eventcore/pull/103/files

I'm just realizing now that it didn't change the `SO_REUSEPORT` flag at all, but the `SO_REUSEADDR` flag.

**Comment by WebFreak001** [comment]
so setting reusePort on HTTPServerOption should fix this?

**Comment by dd86k** [comment]
I think `reusePort` should be on by default, including `SO_REUSEPORT`, which has been implemented since Linux 3.9.

**Comment by WebFreak001** [comment]
`HTTPServerOption.reusePort` seems to have fixed this (though at first it looked like it didn't fix it, but after another restart it worked properly)

So it's probably that change you linked?

I agree with @dd86k that `reusePort` should be the default. What's the reason behind the current default? (off)

**Comment by rracariu** [comment]
> I didn't have the chance to take a closer look, but could this be the reason: https://github.com/vibe-d/eventcore/pull/103/files
> 
> I'm just realizing now that it didn't change the `SO_REUSEPORT` flag at all, but the `SO_REUSEADDR` flag.

I'm the author of that change, and here are the reasons:
On some OpenWRT configurations the `SO_RESUSEADDR` is not supported (not compiled in). This comes from the highly configurable nature of that OS.

The quick fix would be to make the `reusePort` be default on for `version (linux)` and allow one to disable it.
The correct fix would be to add the `reuseAddress` option and make it also default.

**Comment by s-ludwig** [comment]
Added a `reuseAddress` option now and made `StreamListenOptions.defaults == StreamListenOptions.reuseAddress`, meaning on OpenWRT `StreamListenOptions.none` needs to be passed now.
