### ISSUE TITLE
Please update the TechEmpower vibe.d version

### ISSUE THREAD

**Issue by vitalka200** [vibe-d/vibe.d#2283]
Can someone please update the TechEmpower benchmark code to include latest (0.8.5) vibe.d version?

**Comment by kubo39** [comment]
[This commit](https://github.com/TechEmpower/FrameworkBenchmarks/commit/b666fc34ba5eecffa0eb0616c52b62a3729b81bb) updated vibe.d version, can we close this?

**Comment by vitalka200** [comment]
I assume...
