### ISSUE TITLE
Linker error: Error: linker exited with status 1

### ISSUE THREAD

**Issue by shove70** [vibe-d/vibe.d#2296]
OS: Windows 10 x64
DMD: 2.085.1
Vibe.d: 0.8.5, 0.8.6-alpha.1
Compile cmd line: dub
Code:

```
import std.stdio;

import vibe.d;

void main() {
}
```

output:

************  Building D project: d_test2  ************
>> Running `(default)` with: C:\D\dmd2\windows\bin\dub.exe build
Performing "debug" build using C:\D\dmd2\windows\bin\dmd.exe for x86.
taggedalgebraic 0.11.3: target for configuration "library" is up to date.
eventcore 0.8.42: target for configuration "winapi-optlink" is up to date.
stdx-allocator 2.77.5: target for configuration "library" is up to date.
vibe-core 1.6.2: target for configuration "winapi-optlink" is up to date.
vibe-d:utils 0.8.5: target for configuration "library" is up to date.
vibe-d:data 0.8.5: target for configuration "library" is up to date.
mir-linux-kernel 1.0.1: target for configuration "library" is up to date.
vibe-d:crypto 0.8.5: target for configuration "library" is up to date.
diet-ng 1.5.0: target for configuration "library" is up to date.
vibe-d:stream 0.8.5: target for configuration "library" is up to date.
vibe-d:textfilter 0.8.5: target for configuration "library" is up to date.
vibe-d:inet 0.8.5: target for configuration "library" is up to date.
vibe-d:tls 0.8.5: target for configuration "openssl" is up to date.
vibe-d:http 0.8.5: target for configuration "library" is up to date.
vibe-d:mail 0.8.5: target for configuration "library" is up to date.
vibe-d:mongodb 0.8.5: target for configuration "library" is up to date.
vibe-d:redis 0.8.5: target for configuration "library" is up to date.
vibe-d:web 0.8.5: target for configuration "library" is up to date.
vibe-d 0.8.5: target for configuration "vibe-core" is up to date.
d_test2 ~master: building configuration "application"...
Linking...
Error: linker exited with status 1
C:\D\dmd2\windows\bin\dmd.exe failed with exit code 1.
  ^^^ Terminated, exit code: 2 ^^^
************  Build terminated.  ************

**Comment by shove70** [comment]
![WechatIMG51](https://user-images.githubusercontent.com/27794478/56026389-9aefa000-5d46-11e9-8970-f8453dfc4d69.jpeg)

**Comment by ZombineDev** [comment]
This error is well known - it's due to the `x86` build mode. If you have Visual Studio with Visual C++ installed (or the VS Build Tools), you should be able to get this working like this:

```
dub --arch=x86_mscoff
```

Or:

```
dub --arch=x86_64
```

For 32-bit and 64-bit apps respectively.

**Comment by shove70** [comment]
Hi ZombineDev:


> This error is well known - it's due to the `x86` build mode. If you have Visual Studio with Visual C++ installed (or the VS Build Tools), you should be able to get this working like this:

You're right, but it has nothing to do with vibe's dlang code and dmd's performance in x86 mode.
Before vibe-d 0.8.4, there was no problem at all. Only 0.8.4 and 0.8.5 did this happen.

In release 0.8.4, the openssl's lib and DLL were changed, so this is the problem caused by the recently updated library files.

```
< 0.8.4: (./lib/win-i386)
eay.lib
libeay32.dll
ssl.lib
ssleay32.dll

0.8.4 & 0.8.5: (./lib/win-i386)
libcrypto.lib
libcrypto-1_1.dll
libssl.lib
libssl-1_1.dll

```

**Comment by WalterBright** [comment]
The updated libraries need to be in OMF format. If they were only updated with mscoff import libraries, optlink will indeed fail with it (although optlink still shouldn't seg fault).

The solution is to run the mscoff import libraries through coffimplib.
