### ISSUE TITLE
"--override-config vibe-d:tls/none" results to "configuration not found"

### ISSUE THREAD

**Issue by dd86k** [vibe-d/vibe.d#2341]
| | |
|---|---|
| OS | Linux 4.19 (Xubuntu 18.04) |
| dub | 1.15.0 |
| vibe-d | 0.8.5 |

Hello,

As writing this Issue I actually checked the tls dub.sdl and found out that `none` doesn't exist but `notls` exists, which works for me. So this is now a reminder to update the main tutorial found at https://vibed.org/docs#http-https

**Comment by WebFreak001** [comment]
this has been fixed 8 months ago in https://github.com/vibe-d/vibed.org/commit/da846abbabce23197bf8519f8029d2ede4012506 how is this not deployed yet?

**Comment by dd86k** [comment]
Isn't @s-ludwig hosting vibed.org?

**Comment by wilzbach** [comment]
Yep, he's the only one who can do a deploy of vibed.org.

**Comment by s-ludwig** [comment]
I finally deployed the master version now. I had to set up an Ubuntu 16.04 VM to be able to build a binary that is compatible with the VPS on which the registry runs. This is also the reason why I didn't finish an earlier attempt some months ago, as I was running out of time. I have this set up now, but an automated deployment should still somehow be prioritized (whoever can invest the necessary time).

**Comment by dd86k** [comment]
Would an automated deployment system based on the git tagging system work for anyone?

I'm going to close this Issue once I see the `notls` change on /docs#http-https

**Comment by s-ludwig** [comment]
Turns out I was in a hurry and mistakenly deployed code.dlang.org instead of vibed.org. Unfortunately there is a (not very recent) regression in DUB that I just detected now and which required some ugly local workarounds to be able to build vibed.org. It's deployed now, but I'll still have to work on a DUB fix.

**Comment by dd86k** [comment]
Closing issue now since it was deployed. Thanks!
