### ISSUE TITLE
Const violation issue.

### ISSUE THREAD

**Issue by TurkeyMan** [vibe-d/vibe.d#2348]
https://github.com/vibe-d/vibe.d/blob/86c75f91b3342a7726922a2d05365fda96861d78/crypto/vibe/crypto/cryptorand.d#L173

So this line tries to modify a `const` thing.
`auto p = atomicLoad(*cast(const shared GET_RANDOM*) &hasGetRandom);` is `const GET_RANDOM`, then `p` is assigned below.
The reason this compiled is because there was a seriously bad bug where `atomicLoad` receives `shared const T`, and returns `T`, which strips `const` off of anything which passes through.
This can be easily fixed by writing `GET_RANDOM` instead of `auto`.

**Comment by TurkeyMan** [comment]
For reference; this PR fixes the bug: https://github.com/dlang/druntime/pull/2745
vibe.d is broken with master DMD. Thank you! :P

**Comment by Geod24** [comment]
So if I understand correctly, the code actually behaves as intended, but the way it's expressed to the compiler is wrong, right ?

**Comment by TurkeyMan** [comment]
Not sure what you mean?
`atomicLoad` receives `shared const T`, and returns `T`. There was no compile error in the implementation because it piped through inline asm which does full type erasure.

Stripping off shared is fine since it returns a copy, stripping const is *completely* not okay, so I fixed it...

**Comment by TurkeyMan** [comment]
If you mean, there's not actually a bug in vibe.d, that is correct. There's no bug. But auto is inferring not-const for a const thing... it's a trivial fix to not use auto.

**Comment by Geod24** [comment]
> If you mean, there's not actually a bug in vibe.d, that is correct.

Yep, that's what I mean. So there's no harm for the users, good.
