### ISSUE TITLE
Virtual Memory leak in name resolution

### ISSUE THREAD

**Issue by marcioapm** [vibe-d/vibe.d#2378]
There seems to be a memory leak in name resolution. Test on Linux.

Consider the program:

```
import vibe;
foreach (i; 0..1_000_000) {
    resolveHost("google.com");
    sleep(100.msecs);
}
```

The program will allocate massive amounts of virtual memory very fast and never release it.
It won't use much of it at all, but it will consume address space nonetheless, which is very problematic in a number of situations.

I traced it in Valgrind and the virtual memory is `mmap`ed by `pthread_create`, so presumably, it's the new thread's stack.

I am posting it here, but I am not sure if this is an issue with `eventcore` or `std.parallelism`.

**Comment by marcioapm** [comment]
I am using `eventcore` on this particular app.

**Comment by s-ludwig** [comment]
Turned out to be an issue in `std.parallelism`. I've pushed a workaround to eventcore: https://github.com/vibe-d/eventcore/pull/130

**Comment by s-ludwig** [comment]
@Weyzu: I've opened a PR that attempts to fix this: https://github.com/vibe-d/eventcore/pull/131

Since I couldn't reproduce it so far, it would be great if you could build with that branch and verify the fix is working.

**Comment by Weyzu** [comment]
Will do! Thanks for the fast response.
