### ISSUE TITLE
Why do I now need to specify openssl-1.0 as a subConfiguration?

### ISSUE THREAD

**Issue by schveiguy** [vibe-d/vibe.d#2380]
Prior to building today, I did not have to specify (on Linux) a subConfiguration for `vibe-d:tls` of openssl-1.0. I feel like it's something that got installed on my system recently. But now, my application will not link (says it's missing functions such as `BIO_set_init`).

But if I add the subConfiguration of openssl-1.0, it works. Is vibe.d supposed to figure this out automatically? I feel like it was doing fine before, but something in my system broke it. Any ideas?

**Comment by wilzbach** [comment]
Vibe.d tries to detect the OpenSSL version on your system. As the default is 1.1., maybe the detection fails on your machine?

**Comment by Geod24** [comment]
I improved the detection in https://github.com/vibe-d/vibe.d/pull/2401

Before, it was just using the "openssl" binary to detect the version. Can you test with master to see if it solves your issue ? If you have pkg-config it should just work.

**Comment by Geod24** [comment]
> So essentially, you are using the binary which has nothing really to do with which development library is installed.

Yeah that was the same problem on Mac, and fixed in #2401 . Since `pkg-config` is tried first nowadays, that should solve your issue. If you want to test but not mess with your system, a docker image or a chroot would work, no ?

**Comment by schveiguy** [comment]
ok, I "downgraded" and indeed pkg-config does see the right version (can't test to see if it builds because it hasn't been released yet). I think I misunderstood what pkg-config did, I thought it had something to do with the package manager on the OS. Seems like this is exactly the use case it was intended for, so a great solution!

I think this can be closed.

**Comment by Geod24** [comment]
Great! Yes I'm quite happy that `pkg-config` is integrated in DUB. We could probably extend it to allow dependency on a specific version, which would be quite useful for bindings.
