### ISSUE TITLE
Unable to create index om mongo collection

### ISSUE THREAD

**Issue by tirithen** [vibe-d/vibe.d#2394]
Maybe an old way of creating indexes is still used?

The use of system.indexes (https://github.com/vibe-d/vibe.d/blob/master/mongodb/vibe/db/mongo/collection.d#L470) is maybe not supported anymore? (https://jira.mongodb.org/browse/SERVER-10231)

Can I use the more up to date db.mycollection.createIndex() in any way instead?

My attempt to use the existing way was:

    scope const(Tuple!(string, int))[] index1;
    index1 ~= tuple("meta.id", 1);
    collection.ensureIndex(index1);

and that gave:

    vibe.db.mongo.connection.MongoDBException@/home/tirithen/.dub/packages/vibe-d-0.8.6/vibe-d/mongodb/vibe/db/mongo/connection.d(472): cannot write to 'testing.system.indexes'

**Comment by WebFreak001** [comment]
fixed by #2433
