### ISSUE TITLE
mongo: Unable to use runCommand to create index

### ISSUE THREAD

**Issue by tirithen** [vibe-d/vibe.d#2397]
I'm trying to create two indexes by running the command createIndex but I get the error:

    {"ok":0,"codeName":"CommandNotFound","errmsg":"no such command: 'indexes'","code":59}

It looks like it uses the "indexes" key as the command instead of "createIndex". The code I used was this (the query variable is probably the most interesting part):

    void ensureIndex(MongoCollection collection) {
      auto name = collection.name;
      auto database = collection.database;

      database.runCommand(Bson(["create": Bson(name)]));

      auto query = Bson([
          "createIndexes": Bson(name),
          "indexes": Bson([
              Bson([
                "key": Bson(["meta.id": Bson(1)]),
                "name": Bson("meta.id"),
                "unique": Bson(true)
              ]),
              Bson([
                "key": Bson(["meta.streamId": Bson(1), "meta.index": Bson(1)]),
                "name": Bson("meta.streamId_meta.index"),
                "unique": Bson(true)
              ])
            ])
          ]);

      writeln("query: ", query);

      auto result = database.runCommand(query);

      writeln("updated indexes: ", result);
    }

When I run the same command directly in the mongo console it works fine:

    db.runCommand({"createIndexes":"users","indexes":[{"key":{"meta.id":1},"unique":true,"name":"meta.id"},{"key":{"meta.index":1,"meta.streamId":1},"unique":true,"name":"meta.streamId_meta.index"}]})
    {
            "createdCollectionAutomatically" : false,
            "numIndexesBefore" : 1,
            "numIndexesAfter" : 3,
            "ok" : 1
    }

Any suggestions on how to proceed? I tried the ensureIndex method first but that seems to use some outdated MongoDB syntax for the final command sent to the database server.

**Comment by WebFreak001** [comment]
will be fixed by #2327 

which needs to use stuff from #2201 to be backwards compatible

which is probably too big to ever get a review

**Comment by WebFreak001** [comment]
new index commands in new MongoDB fixed by #2433 

As for your issue: it broke because you created a BSON structure from an AA (which doesn't have a defined order) and MongoDB expects bson maps to have order and picks the first field as the command (in this case it was indexes instead of createIndexes)

**Comment by tirithen** [comment]
Sound great!
