### ISSUE TITLE
Deprecation Messages

### ISSUE THREAD

**Issue by EmTee70** [vibe-d/vibe.d#2406]
When compiling my diet templates I am getting the following Messages:
`../../.dub/packages/diet-ng-1.6.0/diet-ng/source/diet/parser.d(787,6): Deprecation: function std.typecons.Nullable!(Node[]).Nullable.get_ is deprecated - Implicit conversion with alias Nullable.get this will be removed after 2.096. Please use .get explicitly.
../../.dub/packages/diet-ng-1.6.0/diet-ng/source/diet/parser.d(788,29): Deprecation: function std.typecons.Nullable!(Node[]).Nullable.get_ is deprecated - Implicit conversion with alias Nullable.get this will be removed after 2.096. Please use .get explicitly.
/usr/include/dmd/phobos/std/range/primitives.d(174,38): Deprecation: function std.typecons.Nullable!(Node[]).Nullable.get_ is deprecated - Implicit conversion with alias Nullable.get this will be removed after 2.096. Please use .get explicitly.
/usr/include/dmd/phobos/std/range/primitives.d(176,27): Deprecation: function std.typecons.Nullable!(Node[]).Nullable.get_ is deprecated - Implicit conversion with alias Nullable.get this will be removed after 2.096. Please use .get explicitly.
/usr/include/dmd/phobos/std/range/primitives.d(1264,26): Deprecation: function std.typecons.Nullable!(Node[]).Nullable.get_ is deprecated - Implicit conversion with alias Nullable.get this will be removed after 2.096. Please use .get explicitly.
/usr/include/dmd/phobos/std/range/primitives.d(1021,27): Deprecation: function std.typecons.Nullable!(Node[]).Nullable.get_ is deprecated - Implicit conversion with alias Nullable.get this will be removed after 2.096. Please use .get explicitly.
/usr/include/dmd/phobos/std/range/primitives.d(1553,38): Deprecation: function std.typecons.Nullable!(Node[]).Nullable.get_ is deprecated - Implicit conversion with alias Nullable.get this will be removed after 2.096. Please use .get explicitly.
/usr/include/dmd/phobos/std/range/primitives.d(2185,15): Deprecation: function std.typecons.Nullable!(Node[]).Nullable.get_ is deprecated - Implicit conversion with alias Nullable.get this will be removed after 2.096. Please use .get explicitly.
/usr/include/dmd/phobos/std/algorithm/iteration.d(598,9): Deprecation: function std.typecons.Nullable!(Node[]).Nullable.get_ is deprecated - Implicit conversion with alias Nullable.get this will be removed after 2.096. Please use .get explicitly.
/usr/include/dmd/phobos/std/algorithm/iteration.d(604,20): Deprecation: function std.typecons.Nullable!(Node[]).Nullable.get_ is deprecated - Implicit conversion with alias Nullable.get this will be removed after 2.096. Please use .get explicitly.
/usr/include/dmd/phobos/std/algorithm/iteration.d(624,20): Deprecation: function std.typecons.Nullable!(Node[]).Nullable.get_ is deprecated - Implicit conversion with alias Nullable.get this will be removed after 2.096. Please use .get explicitly.
`

**Comment by Geod24** [comment]
It's an issue with [diet-ng](https://github.com/rejectedsoftware/diet-ng), not this repository.
However I am not sure if we can fix most of those messages, as they trigger inside of Phobos, not diet-ng.

**Comment by EmTee70** [comment]
Sorry, for being at the wrong place, I have this messages directing into phobos, too:
Compiling Diet HTML template show_running.dt...
`/usr/include/dmd/phobos/std/range/primitives.d(174,38): Deprecation: alias byKeyValue this is deprecated - Iterate over .byKeyValue instead.
/usr/include/dmd/phobos/std/range/primitives.d(176,27): Deprecation: alias byKeyValue this is deprecated - Iterate over .byKeyValue instead.
/usr/include/dmd/phobos/std/range/primitives.d(174,38): Deprecation: alias byKeyValue this is deprecated - Iterate over .byKeyValue instead.
/usr/include/dmd/phobos/std/range/primitives.d(176,27): Deprecation: alias byKeyValue this is deprecated - Iterate over .byKeyValue instead.`

I don't know where to start with this.

**Comment by s-ludwig** [comment]
I just noticed that there were a bunch of fixes in diet-ng master, among them also a `Nullable` warnings fix. I've tagged 1.6.1 with these changes now.

**Comment by EmTee70** [comment]
Great job!
Now only at building of the lib:
`vibe-d:http 0.8.6: building configuration "library"...
../../.dub/packages/vibe-d-0.8.6/vibe-d/http/vibe/http/server.d(949,24): Deprecation: function std.typecons.Nullable!(CookieValueMap).Nullable.get_ is deprecated - Implicit conversion with alias Nullable.get this will be removed after 2.096. Please use .get explicitly.
../../.dub/packages/vibe-d-0.8.6/vibe-d/http/vibe/http/server.d(962,38): Deprecation: function std.typecons.Nullable!(DictionaryList!(string, true, 16LU, false)).Nullable.get_ is deprecated - Implicit conversion with alias Nullable.get this will be removed after 2.096. Please use .get explicitly.
../../.dub/packages/vibe-d-0.8.6/vibe-d/http/vibe/http/server.d(1041,18): Deprecation: function std.typecons.Nullable!(DictionaryList!(string, true, 16LU, false)).Nullable.get_ is deprecated - Implicit conversion with alias Nullable.get this will be removed after 2.096. Please use .get explicitly.
`

**Comment by s-ludwig** [comment]
I *think* this should be fixed in vibe-d 0.9.0-alpha.1 - I'm not sure if it caught all warnings, but at least there was a related pull request.

**Comment by EmTee70** [comment]
Ok. Thank you!!! So I close this one. If it will occur later, I will open a new issue.
