### ISSUE TITLE
dub upgrade issue with vibe-d:core

### ISSUE THREAD

**Issue by schveiguy** [vibe-d/vibe.d#2410]
I'm not sure if this is a dub upgrade issue or a vibe-d issue.

I'm depending on mysql-native, which depends on `vibe-core ~>1.7.0`

vibe-d:core (in vibe-core mode) depends on `vibe-core`, but the revision is `>=1.7.0-rc.2 <2.0.0-0`. See here: https://github.com/vibe-d/vibe.d/blob/v0.8.6/core/dub.sdl#L16

When I tried to do a dub upgrade recently, I ran into this:

```
Unresolvable dependencies to package vibe-core:
  mysql-native 2.3.0+commit.48.g87f0233 depends on vibe-core ~>1.7.0 (optional)
  mysql-native 2.3.0+commit.48.g87f0233 depends on vibe-core ~>1.7.0
  mysql-native 2.3.0+commit.48.g87f0233 depends on vibe-core ~>1.7.0
  vibe-d:core 0.8.6 depends on vibe-core >=1.7.0-rc.2 <2.0.0-0
```

I would have expected this to work. But it may have something to do with the type of range. If I dub add-local a vibe-d copy, put to 0.8.6, and change the field to `>=1.7.0 <2.0.0-0`

I get this error instead, which looks really weird:

```
Unresolvable dependencies to package vibe-core:
  mysql-native 2.3.0+commit.48.g87f0233 depends on vibe-core ~>1.7.0 (optional)
  mysql-native 2.3.0+commit.48.g87f0233 depends on vibe-core ~>1.7.0
  mysql-native 2.3.0+commit.48.g87f0233 depends on vibe-core ~>1.7.0
  vibe-d:core 0.8.6 depends on vibe-core ~>1.7
```

But if I just change it to `~>1.7.0`, it works.

**Comment by s-ludwig** [comment]
I'm pretty sure that this is the same issue as in [the recent build blackout](https://github.com/vibe-d/vibe.d/issues/2284#issuecomment-578800530). In our internal project I actually had to work around issues like this by adding sufficiently strict dependency specification to the root package.

**Comment by Geod24** [comment]
Is this still an issue ?

**Comment by schveiguy** [comment]
Not for me, I've moved on to vibe 0.9.x. My dependencies were a bit weird and non-standard.

So I don't know if I can even test this any more. but a recent build that used the latest stuff didn't have any problems.
