### ISSUE TITLE
REST generator rejects `ref` parameter

### ISSUE THREAD

**Issue by Geod24** [vibe-d/vibe.d#2415]
I have the following code:
```D
import vibe.web.rest;

struct NC
{
    @disable this(this);

    int a;
    string b;
}

interface API
{
    void sendData (ref NC data);
}

void main()
{
    NC nc = NC(42, "42");
    auto client = new RestInterfaceClient!API("127.0.0.1");
    client.sendData(nc);
}
```

The REST generator errors out with:
```
restref ~master: building configuration "application"...
../../../../.dub/packages/vibe-d-0.8.6/vibe-d/web/vibe/web/internal/rest/common.d(59,2): Error: static assert:  "app.API.sendData: Parameter 'data' cannot be ref"
../../../../.dub/packages/vibe-d-0.8.6/vibe-d/web/vibe/web/rest.d(596,23):        instantiated from here: RestInterface!(API)
source/app.d(19,23):        instantiated from here: RestInterfaceClient!(API)
dmd failed with exit code 1.
```

However, since my struct is non-copyable, I cannot make this argument non-ref.
The use case is sending a struct that is `extern(C++)` and contains non-trivial copy constructors (some fields are `std::vector`).

**Comment by s-ludwig** [comment]
I wonder if we could simply allow `auto ref` for that purpose.

**Comment by s-ludwig** [comment]
Another possibility would be `in ref` or some additional UDA+`ref`. Or `ref` could simply be allowed for any parameter, AFAICS the only reason for the check is to avoid misuse by expecting the modified value to propagate to the caller.

**Comment by Geod24** [comment]
Ah, that makes a lot of sense. I think `in ref` would be good (and enough for my use case).

**Comment by Geod24** [comment]
Well, now that `-preview=in` exists, the same error triggers with `in` parameter, and I think it would make a lot of sense to recognize this.
