### ISSUE TITLE
segfault when sending a message to a terminated task

### ISSUE THREAD

**Issue by Panke** [vibe-d/vibe.d#2418]
```
import vibe.vibe;

struct Message
{
}

void main()
{

   runTask(
   {
   	auto tid = Task.getThis().tid;
   	auto t1 = runTask(
      {
     		while (true)
     		{
        		sleep(1.seconds);
        		send(tid, Message.init);
     		}
   	});

   	auto t2 = runTask(
      {
     		sleep(5.seconds);
     		enforce(false, "failure");
   	});

   	while (true)
   	{
      	receive(
         	(Message m) { send(t2, m); }
         );
   	}
	});
	runApplication();
}
```

This segfaults after five seconds. My debugger says that the *mbox* field of the Tid t2 is 0x0.

While sending a message to a terminated task does not make too much sense, do I have any chance to notice it and avoid the segfault?

**Comment by GallaFrancesco** [comment]
I usually check if a task is running by calling the `Task.running` property (defined at [vibe-core/source/vibe/core/task.d:72](https://github.com/vibe-d/vibe-core/blob/3de7cb004279bf4247f755e7ca910d234578e1e6/source/vibe/core/task.d#L72)) before sending a message to it.

That said, segfaults should not happen, so it would be nice to have this check performed by `vibe-core` directly.

**Comment by Panke** [comment]
> Nevertheless segfaults should not happen, so it would be nice to have this check performed by `vibe-core` directly.

I've created a new issue against vibe-core: https://github.com/vibe-d/vibe-core/issues/193


> Edit: try it like this, it should display an error message for the uncaught exception in `t2` and print to stdout instead of segfaulting.

Yes, I'll do something along the line. Thank you very much!
