### ISSUE TITLE
Error on registerWebInterface with a parameterized constructor class

### ISSUE THREAD

**Issue by o3o** [vibe-d/vibe.d#2438]
When I register a class with a parameterized constructor. I get the following error:

```
Error: static assert:  "Instances may only be returned from parameter-less functions (__ctor)!"
```
This happens in all  projects that were successfully built before.
For example:

```
$ git clone git@github.com:rejectedsoftware/diskuto.git
$ cd diskuto/examples/embed-raw
$ dub build

/home/o3o/.dub/packages/vibe-d-0.8.6/vibe-d/web/vibe/web/web.d(200,6): Error: static assert:  "Instances may only be returned from parameter-less functions (__ctor)!"
../../source/diskuto/web.d(33,29):        instantiated from here: registerWebInterface!(DiskutoWebInterface, cast(MethodStyle)5)
dmd failed with exit code 1.
```

My environment
```
$ dmd --version
DMD64 D Compiler v2.091.0

$ dub --version
DUB version 1.16.0-beta.1, built on Jul 22 2019
```
Thank you

**Comment by Geod24** [comment]
So it is failing with v0.8.6. Which version did it last work with ?

**Comment by o3o** [comment]
With 0.8.6 !

I checked  code and Sönke introduced this assert  in 2014

```
commit 5c744e9cd4fedb8a4b9a80aad66f53d51c805cc4
Author: Sönke Ludwig <sludwig@rejectedsoftware.com>
Date:   Tue Jul 22 15:45:43 2014 +0200
 
-				router.match(minfo.method, concatURL(settings.urlPrefix, url), (req, res) {
-					handleRequest!(M, overload)(req, res, instance, settings);
-				});
+				static if (is(RT == class) || is(RT == interface)) {
+					// nested API
+					static assert(
+						ParameterTypeTuple!overload.length == 0,
+						"Instances may only be returned from parameter-less functions ("~M~")!"
+					);
+					auto subsettings = settings.dup;
+					subsettings.urlPrefix = concatURL(settings.urlPrefix, url, true);
+					registerWebInterface!RT(router, __traits(getMember, instance, M)(), subsettings);
+				} else {
+					router.match(minfo.method, concatURL(settings.urlPrefix, url), (req, res) {
+						handleRequest!(M, overload)(req, res, instance, settings);
+					});
+				}
 			}
```

**Comment by o3o** [comment]
I tried:
```
$ dub build  --compiler=ldc
```
It works!

**Comment by Geod24** [comment]
So it sounds like a compiler issue. What LDC version ?

**Comment by o3o** [comment]
I think so...

My ldc:
```
$ ldc --version
LDC - the LLVM D compiler (1.20.1):
  based on DMD v2.090.1 and LLVM 9.0.1
  built with LDC - the LLVM D compiler (1.19.0)
  Default target: x86_64-pc-linux-gnu
  Host CPU: bdver2
  http://dlang.org - http://wiki.dlang.org/LDC
```

**Comment by Geod24** [comment]
Alright, it's a regression introduced by https://github.com/dlang/phobos/pull/7385
The following code:
```D
import std.traits;

class Bar
{
    this (int i) {}
}

static foreach (M; __traits(allMembers, Bar))
{
    static foreach (overload; MemberFunctionsTuple!(Bar, M))
        pragma(msg, M, ": ", ReturnType!overload);
}
```

Would return (pre-2.091.0):
```
toString: string
toHash: ulong
opCmp: int
opEquals: bool
```

After:
```
__ctor: Bar
toString: string
toHash: ulong
opCmp: int
opEquals: bool
```

We need to ignore `__ctor` in Vibe.d, but the regression is still annoying as it prevents compiling older versions of Vibe.d with newer compiler.

**Comment by Geod24** [comment]
Fix submitted in #2439

**Comment by o3o** [comment]
Thank you very much Mathias...

Now fails also with ldc.. :(

**Comment by WebFreak001** [comment]
workaround: remove the constructor, make a private load function and construct it and call that load function before passing to registerWebInterface

**Comment by o3o** [comment]
It's a blocking issue, it stops me from doing my job, WebFreak001 suggestion's it's correct but I've a lot of classes to modify.
@Geod24 can  you create a  just a temporary fork (like [this](https://code.dlang.org/packages/unit-threaded-abscissa))?

Thank you

**Comment by o3o** [comment]
Add a [temporary fork](https://github.com/o3o/vibe.d2438).

**Comment by Geod24** [comment]
@o3o : Sorry I forgot to answer. Personally what I do is use path dependencies + submodules.
You need [this](https://github.com/bpfkorea/agora/blob/c3eef128192bff125a868c7d6be7c16d97bdd5b1/dub.json#L164) and [this](https://github.com/bpfkorea/agora/blob/c3eef128192bff125a868c7d6be7c16d97bdd5b1/dub.selections.json#L22).

The original reason for doing this was to manually override our dependencies' dependencies.
