### ISSUE TITLE
/bin/sh: 1: rdmd: not found

### ISSUE THREAD

**Issue by andre2007** [vibe-d/vibe.d#2442]
I have a docker file based on ubuntu:focal and install these system packages: `build-essential ldc dub`.
While building a project based on vibe-d there is following error:

```
Running pre-generate commands for vibe-d:tls...
/bin/sh: 1: rdmd: not found
```
This is odd and I wonder what can be done to avoid this issue:
- include rdmd in every linux distribution package of ldc
- Replace usage of rdmd in vibe-d (replace it with dub?)

What do you think?

**Comment by Geod24** [comment]
It comes from : https://github.com/vibe-d/vibe.d/blob/ecbdc5d19b55619a75e087e0979e9540311ebbe6/tls/dub.sdl#L29

I thought that LDC was distributing `rdmd` too, is it not the case ? I guess it depends on the packager.

In this specific case you can work around this by using an explicit configuration: https://github.com/vibe-d/vibe.d/blob/ecbdc5d19b55619a75e087e0979e9540311ebbe6/tls/dub.sdl#L69-L99

**Comment by andre2007** [comment]
Thanks.

I will contact the owners of the ldc package (ldmd2 is included but not rdmd) but maybe we should get independent of rdmd as much as possible.

With dub single file packages we should have a good alternative.

**Comment by Geod24** [comment]
Yes I think single-file recipe is the way to go (although there is probably a significant difference in startup time compared to `rdmd`).
We had a similar problem in my application, where we use a D script to build a C++ library. [We ended up going with single-file D package to make it cross-platform](https://github.com/bpfkorea/agora/commit/6cd76d2d44e744846ca695143e1505749e13af75#diff-c440c818ecdf6795a339ff0ad2fba6a0).

**Comment by andre2007** [comment]
https://bugs.launchpad.net/ubuntu/+source/ldc/+bug/1879291

**Comment by Geod24** [comment]
Just to clarify my comment: Not having `rdmd` can make sense for distributions. On Alpine, I packaged it as `dtools-rdmd`. But if you download the zip from Github (directly or through `install.sh`) you'll get it with LDC. I don't know if `rdmd` has the same default mechanism as `dub` (dub will default to whatever compiled it), I *think* it default to the compiler in its current directory, then a few other places, but you'd have to check if LDC's `rdmd` is special in any way.

**Comment by andre2007** [comment]
https://github.com/vibe-d/vibe.d/pull/2443

**Comment by andre2007** [comment]
Fixed.
