### ISSUE TITLE
"Second attempt to send HTTP request failed" message is unhelpful

### ISSUE THREAD

**Issue by Geod24** [vibe-d/vibe.d#2451]
Consider this stack trace:
```
2020-06-11T05:03:17.157815+00:00 app[web.1]: [main(buYb-fin) CRITICAL] Task terminated with uncaught exception: Second attempt to send HTTP request failed.
2020-06-11T05:03:17.162070+00:00 app[web.1]: [main(buYb-fin) dbg] Full error: object.Exception@/app/.dub/packages/vibe-d-0.8.6/vibe-d/http/vibe/http/client.d(615): Second attempt to send HTTP request failed.
2020-06-11T05:03:17.162093+00:00 app[web.1]: [main(buYb-fin) dbg] ----------------
2020-06-11T05:03:17.162126+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? pure @safe bool std.exception.enforce!().enforce!(bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x9fbd8d]
2020-06-11T05:03:17.162164+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? @safe bool vibe.http.client.HTTPClient.doRequestWithRetry(scope void delegate(vibe.http.client.HTTPClientRequest), bool, out bool, out std.datetime.systime.SysTime) [0x9fed82]
2020-06-11T05:03:17.162200+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? @safe vibe.http.client.HTTPClientResponse vibe.http.client.HTTPClient.request(scope void delegate(vibe.http.client.HTTPClientRequest)) [0x9fea33]
2020-06-11T05:03:17.162241+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? @safe vibe.http.client.HTTPClientResponse vibe.http.client.requestHTTP(vibe.inet.url.URL, void delegate(scope vibe.http.client.HTTPClientRequest), const(vibe.http.client.HTTPClientSettings)) [0x9fc690]
2020-06-11T05:03:17.162275+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? @safe vibe.http.client.HTTPClientResponse dlangbot.utils.request(immutable(char)[], scope void delegate(scope vibe.http.client.HTTPClientRequest)) [0x9f9b06]
2020-06-11T05:03:17.162283+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? @safe vibe.http.client.HTTPClientResponse dlangbot.github_api.ghGetRequest(immutable(char)[]) [0x9de1f3]
2020-06-11T05:03:17.162334+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? void dlangbot.app.handlePR(immutable(char)[], dlangbot.github_api.PullRequest*) [0x894d20]
2020-06-11T05:03:17.162348+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? void std.functional.DelegateFaker!(void function(immutable(char)[], dlangbot.github_api.PullRequest*)*).DelegateFaker.doIt(immutable(char)[], dlangbot.github_api.PullRequest*) [0x9137bb]
2020-06-11T05:03:17.162385+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? void vibe.core.task.TaskFuncInfo.set!(void delegate(immutable(char)[], dlangbot.github_api.PullRequest*), immutable(char)[], dlangbot.github_api.PullRequest*).set(ref void delegate(immutable(char)[], dlangbot.github_api.PullRequest*), ref immutable(char)[], ref dlangbot.github_api.PullRequest*).callDelegate(ref vibe.core.task.TaskFuncInfo) [0x914342]
2020-06-11T05:03:17.162418+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? nothrow void vibe.core.task.TaskFiber.run() [0xb464c0]
2020-06-11T05:03:17.162479+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? void core.thread.Fiber.run() [0xc26167]
2020-06-11T05:03:17.162480+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? fiber_entryPoint [0xc2605e]
2020-06-11T05:03:17.162499+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? [0xffffffff]
```

What happened ? Connection closed ? Network error ? I've seen this message quite a few times and I have no idea what went wrong, unless I dig into the internals of Vibe.d.

**Comment by voxluke** [comment]
I have the same problem and cannot solve it. I made only a simple http request. The error comes only, when I read the response (res.readJson();) When I comment out this line, the error is no more. The same happens with res.bodyReader.readAllUTF8() also.

The error log:


"object.Exception@../../../.dub/packages/vibe-d-0.8.6/vibe-d/http/vibe/http/client.d(615): Second attempt to send HTTP request failed.\n----------------\n/usr/include/dlang/dmd/std/exception.d:516 pure @safe void std.exception.bailOut!(Exception).bailOut(immutable(char)[], ulong, scope const(char)[]) [0x56008ff5cfb2]\n/usr/include/dlang/dmd/std/exception.d:437 pure @safe bool std.exception.enforce!().enforce!(bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x56008ff5cf2e]\n../../../.dub/packages/vibe-d-0.8.6/vibe-d/http/vibe/http/client.d:615 @safe bool vibe.http.client.HTTPClient.doRequestWithRetry(scope void delegate(vibe.http.client.HTTPClientRequest), bool, out bool, out std.datetime.systime.SysTime) [0x56008fe6c61f]\n../../../.dub/packages/vibe-d-0.8.6/vibe-d/http/vibe/http/client.d:544 @trusted void vibe.http.client.HTTPClient.request(scope void delegate(scope vibe.http.client.HTTPClientRequest), scope void delegate(scope vibe.http.client.HTTPClientResponse)) [0x56008fe6bf75]\n../../../.dub/packages/vibe-d-0.8.6/vibe-d/http/vibe/http/client.d:108 @safe void vibe.http.client.requestHTTP(vibe.inet.url.URL, void delegate(scope vibe.http.client.HTTPClientRequest), scope void delegate(scope vibe.http.client.HTTPClientResponse), const(vibe.http.client.HTTPClientSettings)) [0x56008fe6ad0b]\n../../../.dub/packages/vibe-d-0.8.6/vibe-d/http/vibe/http/client.d:98 @safe void vibe.http.client.requestHTTP(immutable(char)[], scope void delegate(scope vibe.http.client.HTTPClientRequest), scope void delegate(scope vibe.http.client.HTTPClientResponse), const(vibe.http.client.HTTPClientSettings)) [0x56008fe6ac17]\nsource/doku.d:55 @safe void doku.Doku.makeHTTPRequestJSON(immutable(char)[]) [0x56008fe041ab]\nsource/app.d:52 @safe immutable(char)[] app.PaymentService.getSomeInfo() [0x56008fdd258e]\n../../../.dub/packages/vibe-d-0.8.6/vibe-d/web/vibe/web/rest.d:1527 @trusted immutable(char)[] vibe.web.rest.jsonMethodHandler!(app.APIV1.getSomeInfo(), 0uL, app.PaymentService).jsonMethodHandler(app.PaymentService, ref vibe.web.internal.rest.common.RestInterface!(app.PaymentService).RestInterface).handler(vibe.http.server.HTTPServerRequest, vibe.http.server.HTTPServerResponse).__lambda9() [0x56008fdd9b00]\n../../../.dub/packages/vibe-d-0.8.6/vibe-d/web/vibe/web/rest.d:1527 @safe void vibe.web.rest.jsonMethodHandler!(app.APIV1.getSomeInfo(), 0uL, app.PaymentService).jsonMethodHandler(app.PaymentService, ref vibe.web.internal.rest.common.RestInterface!(app.PaymentService).RestInterface).handler(vibe.http.server.HTTPServerRequest, vibe.http.server.HTTPServerResponse) [0x56008fdd9594]\n../../../.dub/packages/vibe-d-0.8.6/vibe-d/http/vibe/http/router.d:218 @safe bool vibe.http.router.URLRouter.handleRequest(vibe.http.server.HTTPServerRequest, vibe.http.server.HTTPServerResponse).__lambda4!(ulong, immutable(char)[][]).__lambda4(ulong, scope immutable(char)[][]) [0x56008fe80a0b]\n../../../.dub/packages/vibe-d-0.8.6/vibe-d/http/vibe/http/router.d:674 const @safe bool vibe.http.router.MatchTree!(vibe.http.router.Route).MatchTree.doMatch(immutable(char)[], scope bool delegate(ulong, scope immutable(char)[][]) @safe) [0x56008fe832d2]\n../../../.dub/packages/vibe-d-0.8.6/vibe-d/http/vibe/http/router.d:607 @safe bool vibe.http.router.MatchTree!(vibe.http.router.Route).MatchTree.match(immutable(char)[], scope bool delegate(ulong, scope immutable(char)[][]) @safe) [0x56008fe82b6b]\n../../../.dub/packages/vibe-d-0.8.6/vibe-d/http/vibe/http/router.d:211 @safe void vibe.http.router.URLRouter.handleRequest(vibe.http.server.HTTPServerRequest, vibe.http.server.HTTPServerResponse) [0x56008fe806a2]\n../../../.dub/packages/vibe-d-0.8.6/vibe-d/http/vibe/http/server.d:2284 @safe bool vibe.http.server.handleRequest(vibe.internal.interfaceproxy.InterfaceProxy!(vibe.core.stream.Stream).InterfaceProxy, vibe.core.net.TCPConnection, vibe.http.server.HTTPServerContext, ref vibe.http.server.HTTPServerSettings, ref bool, scope stdx.allocator.IAllocator) [0x56008ff123f6]\n../../../.dub/packages/vibe-d-0.8.6/vibe-d/http/vibe/http/server.d:247 @trusted void vibe.http.server.handleHTTPConnection(vibe.core.net.TCPConnection, vibe.http.server.HTTPServerContext).__lambda4() [0x56008ff107f3]\n../../../.dub/packages/vibe-d-0.8.6/vibe-d/http/vibe/http/server.d:239 @safe void vibe.http.server.handleHTTPConnection(vibe.core.net.TCPConnection, vibe.http.server.HTTPServerContext) [0x56008ff104e7]\n../../../.dub/packages/vibe-d-0.8.6/vibe-d/http/vibe/http/server.d:2040 nothrow @safe void vibe.http.server.listenHTTPPlain(vibe.http.server.HTTPServerSettings, void delegate(vibe.http.server.HTTPServerRequest, vibe.http.server.HTTPServerResponse) @safe).doListen(vibe.http.server.HTTPServerContext, bool, bool, bool, bool).__lambda6(vibe.core.net.TCPConnection) [0x56008fe8d75b]\n../../../.dub/packages/vibe-core-1.9.2/vibe-core/source/vibe/core/task.d:699 void vibe.core.task.TaskFuncInfo.set!(void delegate(vibe.core.net.TCPConnection) @safe, vibe.core.net.TCPConnection).set(ref void delegate(vibe.core.net.TCPConnection) @safe, ref vibe.core.net.TCPConnection).callDelegate(ref vibe.core.task.TaskFuncInfo) [0x56009000680e]\n../../../.dub/packages/vibe-core-1.9.2/vibe-core/source/vibe/core/task.d:720 void vibe.core.task.TaskFuncInfo.call() [0x56008ffddc91]\n../../../.dub/packages/vibe-core-1.9.2/vibe-core/source/vibe/core/task.d:426 nothrow void vibe.core.task.TaskFiber.run() [0x56008ffdceab]\n??:? void core.thread.fiber.Fiber.run() [0x5600900e1619]\n??:? fiber_entryPoint [0x5600900e14fe]"

**Comment by voxluke** [comment]
I have made new tests. The problem occures only on Linux. On Windows, the HTTP request works.

**Comment by ferencdg** [comment]
> Consider this stack trace:
> 
> ```
> 2020-06-11T05:03:17.157815+00:00 app[web.1]: [main(buYb-fin) CRITICAL] Task terminated with uncaught exception: Second attempt to send HTTP request failed.
> 2020-06-11T05:03:17.162070+00:00 app[web.1]: [main(buYb-fin) dbg] Full error: object.Exception@/app/.dub/packages/vibe-d-0.8.6/vibe-d/http/vibe/http/client.d(615): Second attempt to send HTTP request failed.
> 2020-06-11T05:03:17.162093+00:00 app[web.1]: [main(buYb-fin) dbg] ----------------
> 2020-06-11T05:03:17.162126+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? pure @safe bool std.exception.enforce!().enforce!(bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x9fbd8d]
> 2020-06-11T05:03:17.162164+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? @safe bool vibe.http.client.HTTPClient.doRequestWithRetry(scope void delegate(vibe.http.client.HTTPClientRequest), bool, out bool, out std.datetime.systime.SysTime) [0x9fed82]
> 2020-06-11T05:03:17.162200+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? @safe vibe.http.client.HTTPClientResponse vibe.http.client.HTTPClient.request(scope void delegate(vibe.http.client.HTTPClientRequest)) [0x9fea33]
> 2020-06-11T05:03:17.162241+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? @safe vibe.http.client.HTTPClientResponse vibe.http.client.requestHTTP(vibe.inet.url.URL, void delegate(scope vibe.http.client.HTTPClientRequest), const(vibe.http.client.HTTPClientSettings)) [0x9fc690]
> 2020-06-11T05:03:17.162275+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? @safe vibe.http.client.HTTPClientResponse dlangbot.utils.request(immutable(char)[], scope void delegate(scope vibe.http.client.HTTPClientRequest)) [0x9f9b06]
> 2020-06-11T05:03:17.162283+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? @safe vibe.http.client.HTTPClientResponse dlangbot.github_api.ghGetRequest(immutable(char)[]) [0x9de1f3]
> 2020-06-11T05:03:17.162334+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? void dlangbot.app.handlePR(immutable(char)[], dlangbot.github_api.PullRequest*) [0x894d20]
> 2020-06-11T05:03:17.162348+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? void std.functional.DelegateFaker!(void function(immutable(char)[], dlangbot.github_api.PullRequest*)*).DelegateFaker.doIt(immutable(char)[], dlangbot.github_api.PullRequest*) [0x9137bb]
> 2020-06-11T05:03:17.162385+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? void vibe.core.task.TaskFuncInfo.set!(void delegate(immutable(char)[], dlangbot.github_api.PullRequest*), immutable(char)[], dlangbot.github_api.PullRequest*).set(ref void delegate(immutable(char)[], dlangbot.github_api.PullRequest*), ref immutable(char)[], ref dlangbot.github_api.PullRequest*).callDelegate(ref vibe.core.task.TaskFuncInfo) [0x914342]
> 2020-06-11T05:03:17.162418+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? nothrow void vibe.core.task.TaskFiber.run() [0xb464c0]
> 2020-06-11T05:03:17.162479+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? void core.thread.Fiber.run() [0xc26167]
> 2020-06-11T05:03:17.162480+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? fiber_entryPoint [0xc2605e]
> 2020-06-11T05:03:17.162499+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? [0xffffffff]
> ```
> 
> What happened ? Connection closed ? Network error ? I've seen this message quite a few times and I have no idea what went wrong, unless I dig into the internals of Vibe.d.

I checked the code, and it happens only if we have persistent tcp connections(and we have that by default with REST). For persistent connections there is a retry logic: if we fail first, then we retry second time. If we fail second time, then we throw this exception. 

I think this is the correct logic, should we change anything at all?

Maybe our agora node was busy and didn't reply within TCP read timeout or within the keep-alive timeout

**Comment by ferencdg** [comment]
> Consider this stack trace:
> 
> ```
> 2020-06-11T05:03:17.157815+00:00 app[web.1]: [main(buYb-fin) CRITICAL] Task terminated with uncaught exception: Second attempt to send HTTP request failed.
> 2020-06-11T05:03:17.162070+00:00 app[web.1]: [main(buYb-fin) dbg] Full error: object.Exception@/app/.dub/packages/vibe-d-0.8.6/vibe-d/http/vibe/http/client.d(615): Second attempt to send HTTP request failed.
> 2020-06-11T05:03:17.162093+00:00 app[web.1]: [main(buYb-fin) dbg] ----------------
> 2020-06-11T05:03:17.162126+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? pure @safe bool std.exception.enforce!().enforce!(bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x9fbd8d]
> 2020-06-11T05:03:17.162164+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? @safe bool vibe.http.client.HTTPClient.doRequestWithRetry(scope void delegate(vibe.http.client.HTTPClientRequest), bool, out bool, out std.datetime.systime.SysTime) [0x9fed82]
> 2020-06-11T05:03:17.162200+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? @safe vibe.http.client.HTTPClientResponse vibe.http.client.HTTPClient.request(scope void delegate(vibe.http.client.HTTPClientRequest)) [0x9fea33]
> 2020-06-11T05:03:17.162241+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? @safe vibe.http.client.HTTPClientResponse vibe.http.client.requestHTTP(vibe.inet.url.URL, void delegate(scope vibe.http.client.HTTPClientRequest), const(vibe.http.client.HTTPClientSettings)) [0x9fc690]
> 2020-06-11T05:03:17.162275+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? @safe vibe.http.client.HTTPClientResponse dlangbot.utils.request(immutable(char)[], scope void delegate(scope vibe.http.client.HTTPClientRequest)) [0x9f9b06]
> 2020-06-11T05:03:17.162283+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? @safe vibe.http.client.HTTPClientResponse dlangbot.github_api.ghGetRequest(immutable(char)[]) [0x9de1f3]
> 2020-06-11T05:03:17.162334+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? void dlangbot.app.handlePR(immutable(char)[], dlangbot.github_api.PullRequest*) [0x894d20]
> 2020-06-11T05:03:17.162348+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? void std.functional.DelegateFaker!(void function(immutable(char)[], dlangbot.github_api.PullRequest*)*).DelegateFaker.doIt(immutable(char)[], dlangbot.github_api.PullRequest*) [0x9137bb]
> 2020-06-11T05:03:17.162385+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? void vibe.core.task.TaskFuncInfo.set!(void delegate(immutable(char)[], dlangbot.github_api.PullRequest*), immutable(char)[], dlangbot.github_api.PullRequest*).set(ref void delegate(immutable(char)[], dlangbot.github_api.PullRequest*), ref immutable(char)[], ref dlangbot.github_api.PullRequest*).callDelegate(ref vibe.core.task.TaskFuncInfo) [0x914342]
> 2020-06-11T05:03:17.162418+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? nothrow void vibe.core.task.TaskFiber.run() [0xb464c0]
> 2020-06-11T05:03:17.162479+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? void core.thread.Fiber.run() [0xc26167]
> 2020-06-11T05:03:17.162480+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? fiber_entryPoint [0xc2605e]
> 2020-06-11T05:03:17.162499+00:00 app[web.1]: [main(buYb-fin) dbg] ??:? [0xffffffff]
> ```
> 
> What happened ? Connection closed ? Network error ? I've seen this message quite a few times and I have no idea what went wrong, unless I dig into the internals of Vibe.d.

I would suggest removing this enforce to have a consistent behaviour. Below is why:

I checked the code, and this Exception happens only if we have persistent connections(and we have that by default with REST thanks to http keepalive being set to true by default). 
For persistent connections there is a retry logic: if we receive an EMPTY response, then we retry one more time. If we receive an EMPTY response second time, then we throw this exception. However this behavior is inconsistent with the non-persistent connections. For non-persistent connections if we receive an EMPTY response, we just forward this empty response to the constructor of the HTTPClientResponse and that constructor throws due to not having 'HTTP 1/...' as the first line. To be consistent with the non-persistent connections, we should remove this 'enforce' check.

So how did we get this Exception in our application in the first place? I think the server just didn't return anything and closed the connection. This shouldn't happen when using Rest based Server as Rest server will always writes something back. (the comment below from voxluke didn't use rest server to send back result, he is calling something called doku(payment service I think) which uses a http client)
