### ISSUE TITLE
vibe.d application runs in the background after closing

### ISSUE THREAD

**Issue by erdemoncel** [vibe-d/vibe.d#2463]
Even simplest application doesn't close properly and still runs in the background.

Let's make a simple vibe.d application

$ dub init merhaba -t vibe.d

$ cd merhaba

$ dub

Program runs  as expected for the first time. 

Terminate the program with CTRL-C. 

If you try to run the program second time.

[vibed_error.txt](https://github.com/vibe-d/vibe.d/files/5036146/vibed_error.txt)
 
You get an error message mentioning port is already in use.

If you check the program is still running in the background

$ ps -ux | grep merhaba
erdem    30301  0.0  0.2  73148 12064 pts/17   S    18:53   0:00 ./merhaba
erdem    30536  0.0  0.0  15640  1004 pts/17   S+   18:58   0:00 grep --color=auto merhaba

If you explicitly kill the program 

$ kill -9 30301

at the end program terminates. 

But terminating the programs with this method may not be suitable. 

I think this is the vibe.d's most important bug. I used other web frameworks but they don't have a problem like that.

**Comment by jblachly** [comment]
I agree this is the most important bug to address -- the most basic tutorial , indeed the dub-initiated template, suffers from this. Until the enterprising new developer things to run `ps` and `kill`, the application will thereafter fail to start.

**Comment by jblachly** [comment]
Duplicated in #2436 and #205 ; the latter provides a solution although not documented and unclear why it works.

**Comment by erdemoncel** [comment]
I've made a few tests. After adding this section to dub.json,

> "versions": [ "VibeHighEventPriority" ]

it seems to be working fine.

**Comment by Geod24** [comment]
The issue has been fixed as of eventcore v0.9.11
