### ISSUE TITLE
Release v0.9.3

### ISSUE THREAD

**Issue by PetarKirov** [vibe-d/vibe.d#2502]
<details>
  <summary>slightly off-topic rant</summary>

For a long time vibe.d (along with many other D projects (notably DCD and it's dependencies) used the practice of tagging many alpha and beta releases (e.g. `v0.9.3-alpha.2`) instead of directly releasing a patch release, when there are no (at least no expected) breaking changes. In some [extreme cases (not vide.d related)](https://github.com/dlang-community/libdparse/tags) we've had 15 alpha tags and 8 beta tags, which left users without an "official" release for almost 12 months.
I understand that this is a way to protect users (`dub` by default won't update to `x.y.z-*` versions), but I still don't understand why this overly sensitive practice is the default, while in many cases tagging a new patch release is just fine. Another negative of waiting for changes to accumulate is that it makes releases larger, which is always bad - they take longer and can contain more breaking changes.

I'd even prefer tagging each merge commit as a separate patch release (no matter how "noisy" this may look), than waiting for things to be "polished". If one wants bigger, more polished releases, we should really be using minor SemVer for that.
If one is implementing a new feature (e.g. HTTP3 support) and doesn't want to do all the work in a separate branch (as it can be annoying to resolve merge conflicts if development on master is also progressing quickly in the mean time), I'd suggest merging often small bits and pieces in master, but keeping them disabled under a `version (NewFeature_XXX)`, so there is no risk for users to use code that is not ready.

---

</details>

Are there any blockers? Anything planned to be merged before the new release is tagged?

**Comment by Geod24** [comment]
I think we just need more people to keep an eye on Vibe.d, because at the moment it's a one-man effort. @s-ludwig are there other stakeholders that could be given commit access ? I'm thinking of @PetarKirov for example :)
For what it's worth, when we had issues with Vibe.d, I tagged patch and minor releases frequently (e.g. there were 3 eventcore releases in August). But @s-ludwig has stated a preference for the alpha approach IIRC. I'll try to dig up the discussion.

**Comment by s-ludwig** [comment]
The serialization additions just need to be reviewed again before the release can be tagged.

**Comment by Geod24** [comment]
The release happened on January 29th.
