### ISSUE TITLE
Botan as optional dependency?

### ISSUE THREAD

**Issue by andre2007** [vibe-d/vibe.d#2504]
Does it make sense to mark botan as optional? Therefore it is downloaded only if needed?
Also botan provides different configurations. Maybe it makes sense to choose a specific one, to decrease the build/link time.

**Comment by Geod24** [comment]
Botan *is* optional, since it's selected using a (non-default) configuration.
However, due to https://github.com/dlang/dub/issues/1706 it gets downloaded anyway.
Closing as an external bug, let me know if I missed something.
