### ISSUE TITLE
HTTP request reusing TCP connection leads to wrong response being processed

### ISSUE THREAD

**Issue by ferencdg** [vibe-d/vibe.d#2506]
This issue is related to https://github.com/bpfkorea/agora/issues/1395#issuecomment-737626414

Here is how to reproduce:
```D
interface ServiceI
{
    @safe:
    
    StructA getTest ();
    StructA getTest2 ();
}
```
using the clients:

code to reproduce:

```D
setLogLevel(LogLevel.info);
auto settings = new HTTPServerSettings;
settings.port = 5000;
settings.bindAddresses = ["127.0.0.1"];
auto router = new URLRouter;
router.registerRestInterface(new Service);
auto server_addr = listenHTTP(settings, router);

runTask({
	scope (exit) exitEventLoop();
	auto settings = new RestInterfaceSettings();
	settings.httpClientSettings = new HTTPClientSettings();
	settings.httpClientSettings.readTimeout = 1.seconds;
	settings.baseURL = URL("http://127.0.0.1:5000/");
	auto service_client = new RestInterfaceClient!IService(settings);
	try {service_client.getTest(2000);} catch (Exception e) {}
	sleep(1200.msecs);
	auto result = service_client.getTest2(500);
	writeln("result:", result);
	assert(result.i == 500);
});

runApplication();
```

produces
```
[main(----) INF] Listening for requests on http://127.0.0.1:5000/
getTest receiving request with wait: 2000
getTest returning request with wait: 2000
result:TestStruct(2000)
core.exception.AssertError@source/tests.d(83): Assertion failure
----------------
??:? [0x5615a6884c05]
??:? [0x5615a68ad736]
??:? [0x5615a6890c3d]
??:? [0x5615a688479c]
/home/dan/dev/sandbox/sandbox-dlang/source/tests.d:83 [0x5615a662d4f1]
/home/dan/dev/sandbox/sandbox-dlang/../../../.dub/packages/vibe-core-1.11.1/vibe-core/source/vibe/core/task.d:712 [0x5615a666b3ac]
task.d:730 [0x5615a680a791]
task.d:439 [0x5615a6809edb]
??:? [0x5615a68869da]
[1]    171907 abort (core dumped)  ./build/app

```

The call to restClient.getTest2() might return the result that was intended for restClient.getTest() if the following happens:

1. restClient.getTest() uses a timeout of 3 seconds
2. the REST server is busy and only responds after the 3 seconds timeout
3. restClient.getTest2() will reuse the previously opened TCP connection that belongs to the restClient.getTest() call
4. because the serialization format of getTest1 is the same as for getTest2 the REST framework will not throw any errors

**Comment by Geod24** [comment]
Slightly edited the title, trying to be more precise about the causes and the consequence.
Looking at the code, it feels like the example provided is missing a critical part, the concurrency. I don't think this bug can trigger without multiple requests being sent in parallel, can it ?

**Comment by yazd** [comment]
This issue has reproducible code:
https://github.com/vibe-d/vibe.d/issues/1736

**Comment by omerfirmak** [comment]
> Slightly edited the title, trying to be more precise about the causes and the consequence.
> Looking at the code, it feels like the example provided is missing a critical part, the concurrency. I don't think this bug can trigger without multiple requests being sent in parallel, can it ?

I believe it can. The concurrency just makes it easier to trigger it.

**Comment by ferencdg** [comment]
> Slightly edited the title, trying to be more precise about the causes and the consequence.
> Looking at the code, it feels like the example provided is missing a critical part, the concurrency. I don't think this bug can trigger without multiple requests being sent in parallel, can it ?

it can trigger without concurrency, I just updated the issue ticket with an example
