### ISSUE TITLE
JSON errors need to be much more user-friendly

### ISSUE THREAD

**Issue by Geod24** [vibe-d/vibe.d#2546]
Currently, if one does an incorrect binding for a REST interface, one gets this wonderful message:
```
[main(pdXv) dia] Full exception: std.json.JSONException@../../../.dub/packages/vibe-d-0.9.3/vibe-d/data/vibe/data/json.d(2084): Expecting ',' or '}', not '{'.
```

No mention of what went wrong, just an internal parsing error. In my case, it was because the struct had the format `{ "foo": "bar", "data": { "more": "fields here" } }` instead of having all fields at the same level. Obvious in hindsight, but the error message did nothing to help.

**Comment by SingingBush** [comment]
reported this in 2016 (#1615) and a pull request was made by gedaiu (#1622) but it never got merged.

**Comment by gedaiu** [comment]
I usually get the json and paste it in a proper json parser/formater and inspect it. This is the fastest way for debugging this issues...

**Comment by Geod24** [comment]
Duplicate of #1961
