### ISSUE TITLE
Router match setup seems slow

### ISSUE THREAD

**Issue by schveiguy** [vibe-d/vibe.d#2572]
My vibe.d server currently has 247 routes (not sure exactly what that count means, this is the list of routes from `router.getAllRoutes()`).

On first page load, the server takes about 3-4 seconds to decide to deliver the first page. After that, it's very quick.

I've narrowed it down to the `MatchGraphBuilder.disambiguate` function, which is taking the time.

It seems heavy for only 247 routes to consume 4 seconds of runtime to be sorted/stored. I understand that the goal is to increase the speed of the server when matching a route request against the list of routes. I don't really know how the algorithm works. But my concern is that the algorithm for disambiguating is growing somewhat exponentially.

This issue report is just a request for someone to look at it, in case it's something that can be helped with a faster algorithm or maybe a more middle-ground compromise. Perhaps it should just be closed, if this is par for the course in other web servers.

**Comment by s-ludwig** [comment]
I don't really remember whether I made any attempt to optimize the disambiguation step so far, but I'm pretty sure that there are places that can be optimized. If I remember correctly, the algorithm is something like O(n*m), where n is the number of routes and m is the number of characters in route patterns, so effectively O(n²), considering that route patterns all have bounded length. But there are also some rather costly assertions, which we could `version` out.

BTW, it's possible to call `router.rebuild()` before `listenHTTP` to at least avoid delaying the first request.

**Comment by schveiguy** [comment]
Yeah I leave assertions on in my build as this is only a small internal web app with at most 15 users. I hadn’t thought of trying an optimized build. Will try that and get back.

**Comment by schveiguy** [comment]
With an optimized build, the time to construct the tree is 700-800 ms (thanks for the tip on `rebuild`, I was able to time that exactly). That seems pretty reasonable, I'd have to look deeper at it to see how it works if there's any better way to do it, but my concerns are mostly alleviated here.

It might be good to put costly assertions behind a version (I'm assuming these are tree verification assertions?)
