### ISSUE TITLE
Critical crash in error handler (HTTPServerSettings.errorPageHandler)

### ISSUE THREAD

**Issue by dd86k** [vibe-d/vibe.d#2580]
Working on a debugging project that keeps a thread alive by using concurrency members (so, a Task) for OS services. But the server kept crashing, so I tried every possible combination: Semaphores, other kinds of Task, manual threading, etc. Didn't crash like this before, no stack traces and nothing. Both Windows and Linux (Ubuntu). Any compiler (DMD/LDC).

Then I remembered I recently touched the error page handler.

After a bit I found out the `writeJsonBody` function was causing the crash. I did not touch the assignment for the error delegate (`svr_opts.errorPageHandler = toDelegate(&hError);`) so here's a minimum snippet:
```D
@safe
void hError(HTTPServerRequest req, HTTPServerResponse res, HTTPServerErrorInfo errin) {
	import vibe.data.json : Json;
	res.writeJsonBody(Json([
		"status": Json(1),
		"message": Json(errin.exception.msg)
	]));
}
```

Workaround for now is just using `std.format` (since it's simple anyway).

Could be more than just that (since I am handling threads outside of the error handler, in another module).

If need be, I can do a more complete example to make it crash again.

**Comment by Geod24** [comment]
From a quick look, it could simply be because `errin.exception` is null. The doc does say "if any":
https://github.com/vibe-d/vibe.d/blob/a4bf7883c34798a1c8a7aba4c739625e07727f70/http/vibe/http/server.d#L544-L545

The call is made from:
https://github.com/vibe-d/vibe.d/blob/a4bf7883c34798a1c8a7aba4c739625e07727f70/http/vibe/http/server.d#L2157-L2169

And for a 404 no exception is provided:
https://github.com/vibe-d/vibe.d/blob/a4bf7883c34798a1c8a7aba4c739625e07727f70/http/vibe/http/server.d#L2308

**Comment by dd86k** [comment]
Thank you for the reply.

A probable oops on my side. What's odd is, even when put in a try/catch, it would lead to a hard crash. No stack trace and all. Maybe I did just fell into some beginner trap.

I'll close this, since it seems like a non-issue. I could contribute and do a good pass on the documentation, though.

**Comment by Geod24** [comment]
> What's odd is, even when put in a try/catch, it would lead to a hard crash. No stack trace and all. Maybe I did just fell into some beginner trap.

Well, segmentation faults do not lead to an exception / error being thrown in D, like they would in Java.
There are ways to do that (https://github.com/dlang/druntime/blob/master/src/etc/linux/memoryerror.d) but it depends on the OS used (e.g. this works on Linux only, but could probably be extended), as D, while it has a runtime, doesn't have a VM like Java.
