### ISSUE TITLE
MongoDB collection doesn't seem to allow more than 50 documents

### ISSUE THREAD

**Issue by TimCoraxAudio** [vibe-d/vibe.d#2610]
Hi there,

I am looping over a bunch of stored documents that I need to store into the db but after the collection has 50 documents it won't allow any more insertions. From what I can tell MongoDB allows unlimited documents within a collection, is this not true? Can someone confirm whether this is a driver or library issue?

**Comment by Geod24** [comment]
Was it an oversight / user error ? If you don't mind, could you provide a quick summary, in case someone else makes the same error ?

**Comment by TimCoraxAudio** [comment]
Oh, it was just that robo3t was only showing me 50 documents. If I get the mongo shell to dump out the collection it has all the data I need in it. Silly user error
