### ISSUE TITLE
fail to set path which has a ":" in endpoint

### ISSUE THREAD

**Issue by vajrabisj** [vibe-d/vibe.d#2671]
I need to use gcloud NLP api which has the url and endpoint like this "https://language.googleapis.com/v1beta2/documents:analyzeSentiment". The ":" between documents and analyzeSentiment make a lot trouble for me. Just don't know how to setup the @path in RestInterface for such endpoint. I tried many, including `/documents:analyzeSentiment` but all failed, cannot go to the right path...

any idea? thank in advance.

**Comment by thaven** [comment]
`:` is a reserved character in URLs. You should urlencode it like `%3A`.
