### ISSUE TITLE
Error undefined Bufferedstram

### ISSUE THREAD

**Issue by EliuDedupely** [vibe-d/vibe.d#2692]
Error undefined: `vibe-d\stream\vibe\stream\bufferedstream.d(192,13): Error: template instance `isClosableRandomAccessStream!S` template `isClosableRandomAccessStream` is not defined`

**Comment by s-ludwig** [comment]
Which version of vibe-core is in use for that build? `isClosableRandomAccessStream` is there since 1.22.0, maybe it is still building with an older version?

**Comment by EliuDedupely** [comment]
> Which version of vibe-core is in use for that build? `isClosableRandomAccessStream` is there since 1.22.0, maybe it is still building with an older version?

Okay. perfect if I think it's the same version now causes other compatibility problems with other packs. thanks
