### ISSUE TITLE
Any way to write headers after response handler returns?

### ISSUE THREAD

**Issue by kyleingraham** [vibe-d/vibe.d#2738]
I'm working on putting together default middleware in a vibe.d-based web application framework I've been experimenting with [here](https://github.com/kyleingraham/potcake/tree/trunk). I can [add middleware](https://github.com/kyleingraham/potcake/blob/trunk/http/potcake/http/router.d#L223) that runs after a request has been routed successfully. Each middleware in the chain is called before and after the route's handler provided that no short-circuiting occurs. Where I'm running into issues is that I would like to write headers after the route's handler has returned. That fails because the handler has already written a body by then and so my headers are ignored. Does anyone have suggestions for ways to do this? It seems I'd have to delay body writes somehow until the last middleware returned.

I'm hoping to be able to guarantee a header will be written if a certain middleware is added.

**Comment by s-ludwig** [comment]
I don't think there is a reasonable way to achieve this right now. You could probably abuse `createTestHTTPServerResponse` and then later write the buffered reponse body to the real response object, but that would be needlessly wasteful. The only way to make this work reasonably would be to introduce a `void delegate(scope HTTPServerResponse)` callback in `HTTPServerSettings` and let `HTTPResponse.writeHeader` call that just before starting to do its job.

**Comment by kyleingraham** [comment]
Thanks @s-ludwig. I had come to similar conclusions as you on this and decided to stick with writing headers before the request's body is written. Other solutions seemed a bit more complex than I was willing to support. (My middleware experiment has been going pretty well: https://github.com/kyleingraham/potcake/blob/add-csrf-protection/web/potcake/web/middleware.d)

Thanks again for giving this a thought for me 🙏. I'll go ahead and close this issue.
