### ISSUE TITLE
Proposal: remove whole Meson support at all

### ISSUE THREAD

**Issue by denizzzka** [vibe-d/vibe.d#2753]
I suggest to stop pretending that everything is fine with Meson support and propose to remove whole Meson support at all from Vibe.d and its dependencies(!) which are run by Vibe.d community

I tried to build current `~master` with latest Meson (version 1.2.3):
```
$ ~/Dev/meson/meson.py setup check_meson_build
utils/meson.build:33:17: ERROR: File vibe/utils/memory.d does not exist.
```

And I look into this about once every few months and nothing was changed. Previously it was told that someone using this Meson scripts (https://github.com/vibe-d/vibe.d/issues/2531#issuecomment-866710499), but I think that this is no longer true due to the fact that the scripts are still broken.

Also, I don't propose to fix these scripts because way they were written is weak from the beginning because the Meson was just in early state. Instead of correcting Meson scripts it need to be completely rewritten in accordance with modern Meson requirements. And this should be done by the who actually use these scripts. And this must be done simultaneously in all dependencies, which is an almost impossible task (as for me)

**Comment by s-ludwig** [comment]
I tend to agree, since I have no clue about the Meson scripts and can otherwise just leave them dysfunctional. Also, AFAIR, the original intent was to get the libraries packaged for Debian, which, due to the brittle ABI compatibility is not really a desirable approach, in my opinion.

Just an idea, but wouldn't it instead be possible to write a little script that uses the DUB package recipes (via `dub describe`) to generate the Meson scripts for a whole dependency tree and maintain that in a separate repository that contains a bunch of relevant libraries? That is, of course, if somebody has enough interest and knowledge to do so.

**Comment by denizzzka** [comment]
I tried to make such an automatic generator, but abandoned when realized that it generates a monstrously configuration files, which will then be impossible to maintain.

Meson and DUB have different approaches. Any addition of some simple DUB config option is a step to combinatorial explosion of "abilities matrix" of a generated Meson config.

**Comment by denizzzka** [comment]
@foresto 

> As such, I hope the meson files will not be removed.

In fact, it did not exist as working config, so it can be considered as not deleted too

> @denizzzka, I tried your PR #2730 and the matching PRs for vibe-core and eventcore. Thanks for those. With a few more tweaks, I got a successful meson build. That shows that most of the work is done already;

No, initially there were hacks and I just tried to fix them, but I abandoned them because it was futile.

It is need to write Meson support from scratch. By the way, this is not difficult, you don’t need to consider that this removal is some kind of tragedy. (By the way, i forgot about `vibe-core` and `taggedalgebraic`)

I myself am a big fan of the Meson and I think that this removal is the first step towards a normal Meson support

> It's worth noting that Debian releases are generally more than a year apart, so the meson configs would still be useful even if updated infrequently.

Meson configs was in broken state about 2-3 years before removal

**Comment by denizzzka** [comment]
> (By the way, i forgot about vibe-core and taggedalgebraic)

https://github.com/s-ludwig/taggedalgebraic/pull/73

**Comment by denizzzka** [comment]
This issue fixed in https://github.com/vibe-d/vibe.d/commit/7de62abaf67872972d291ceb7dfbfc0629d197af

**Comment by denizzzka** [comment]
@foresto Perhaps this has lost its relevance - https://github.com/mesonbuild/meson/pull/10045

**Comment by s-ludwig** [comment]
@denizzzka Just to be sure I understand this correctly - does that mean that Meson, with that change, is able to successfully build vibe.d directly from its DUB recipes?

**Comment by denizzzka** [comment]
@s-ludwig yes. It just calls `$ dub build blah-blah` as usual

Only little issue remains: https://github.com/mesonbuild/meson/pull/12143

**Comment by denizzzka** [comment]
Also, Meson scripts almost work too

meson.build drafts mentioned above:
```
1/4 taggedalgebraic / test_taggedalgebraic        OK              0.02s
2/4 eventcore / test_eventcore                    OK              0.02s
3/4 stdx-allocator / stdx-allocator-test          OK              0.10s
4/4 vibe-core / vibe-test_core                    FAIL           15.79s   killed by signal 11 SIGSEGV
```
Don't know why vibe-core tests fails, need investigate it if anyone interested
