### ISSUE TITLE
Files are not uploaded using nested paths

### ISSUE THREAD

**Issue by AlexanderZhirov** [vibe-d/vibe.d#2776]
How do I make files visible for nested paths `http://localhost/profile/test`?

```
router.get("/profile", &getReq);
router.get("/profile/test", &getReq);
router.get("*", serveStaticFiles(buildPath(datapath, "public")));
router.get("*", serveStaticFiles(buildPath(datapath, "images")));
router.get("*", serveStaticFiles(buildPath(datapath, "js")));
```

![изображение](https://github.com/vibe-d/vibe.d/assets/37277056/0e0d1e69-09c1-4a91-aaa5-91a10b5e119b)

**Comment by AlexanderZhirov** [comment]
It doesn't load like that either

```
    router.get("/", &getReq);
    router.get("*", serveStaticFiles(buildPath(datapath, "public")));
    router.get("*", serveStaticFiles(buildPath(datapath, "images")));
    router.get("*", serveStaticFiles(buildPath(datapath, "js")));
    auto profile = new URLRouter("/profile");
    profile.get("/", &getReq);
    profile.get("/test", &getReq);
    profile.get("*", serveStaticFiles(buildPath(webHost.data, "public")));
    profile.get("*", serveStaticFiles(buildPath(webHost.data, "images")));
    profile.get("*", serveStaticFiles(buildPath(webHost.data, "js")));
    router.any("*", profile);
```

**Comment by AlexanderZhirov** [comment]
In the files, `dt` specified the path to the files from the root `/style.css` and now, with any path from the root, files are loaded into the page, instead of `style.css`. My mistake.

**Comment by AlexanderZhirov** [comment]
From the point of view of functionality, will a redirect to a nested router be considered correct?

```
router.get("/profile", staticRedirect("profile/", HTTPStatus.movedPermanently));
```

**Comment by s-ludwig** [comment]
The `staticRedirect` is a correct approach when using the `URLRouter` directly. One thing to also consider, which can simplify the route setup considerably, is the `vibe.web.web` module ([`registerWebInterface`](https://vibed.org/api/vibe.web.web/registerWebInterface)). This will do the redirect automatically and can also infer the routes automatically. It would look something like this:

```
void main()
{
    auto router = new URLRouter;
    router.registerWebInterface(new ProfileService);
}

@path("/profile")
class ProfileService {
    // automatically matched as GET /profile and /profile/
    void get(HTTPServerRequest req, HTTPServerResponse res) {
        // 
    }

    // matched as GET /profile/test and /profile/test/
    void getTest(HTTPServerRequest req, HTTPServerResponse res) {
        // 
    }
}
```

If you are working with forms, it will also support conversion and validation of form fields by simply declaring them as method parameters.

**Comment by s-ludwig** [comment]
Yes, that should work, `registerWebInterface` can be called as many times as needed with the same `URLRouter`, with different path prefixes and different class instances.

**Comment by AlexanderZhirov** [comment]
@s-ludwig Everything worked out, thanks a lot for your help! :relaxed:
