### ISSUE TITLE
Implement scrypt function for better password protection

### ISSUE THREAD

**Issue by ilya-stromberg** [vibe-d/vibe.d#415]
We can use original Tarsnap library as initial point (it's under the `2-clause BSD` license that should be compatible with `MIT` license):
https://www.tarsnap.com/download.html

Also, we should deprecate/remove `generateSimplePasswordHash` function.

See also #350.

**Comment by WebFreak001** [comment]
was deprecated/removed ultimately in #2365 (so can be closed)

**Comment by Geod24** [comment]
Thanks!
