### ISSUE TITLE
Add ability to limit amount of started sessions

### ISSUE THREAD

**Issue by ilya-stromberg** [vibe-d/vibe.d#428]
We should add ability to limit amount of started sessions per user and all started sessions. It can be important for `MemorySessionStore`.
For example, we store 50 bytes in every started session (it's not so much) and we have 1_000 new sessions per second (it's not so terrible (D)DOS). After 24 hours we will have ~4GB of RAM usage:
50_1000_60_60_24 = 4 320 000 000 bytes ~4GB
It's definitely too much memory usage.

**Comment by Geod24** [comment]
This fits into #405 which is more general. However this specific need is covered by https://github.com/vibe-d/vibe.d/pull/2496 . This is what we are using to ban clients when using `vibe.web.rest`.
