### ISSUE TITLE
Unix sockets' support

### ISSUE THREAD

**Issue by nazriel** [vibe-d/vibe.d#500]
Discussion: http://forum.rejectedsoftware.com/groups/rejectedsoftware.vibed/thread/10870/

I have a WIP branch https://github.com/nazriel/vibe.d/commits/unix_sockets related to this (source/vibe/web/web.d  change is unrelated, sorry)

But I am not sure if I am going towards right direction API wise etc.
@s-ludwig could you look at this please?
Thanks!

**Comment by JustDevZero** [comment]
First of all, let me say I hate the kinda +1, or "bump" posts, but this is one of that kind :/

@s-ludwig Sorry to bothering you, but there has been some progress about that stuff?

I tried searching over the code to see if there was something fairly implemented, but have given up without success.

This option would be extremely interesting, because the projects would easily coexist with existing ones on our machines, besides the improvement would involve.

**Comment by TETYYS** [comment]
First of all, let me say I hate the kinda +1, or "bump" posts, but this is one of that kind :/

**Comment by skoppe** [comment]
I am using it to talk to the docker daemon. It only works with libevent, but that is ok for me.

**Comment by TETYYS** [comment]
very nice

**Comment by liveresume** [comment]
Is it possible to use listenUDP() with a unix socket? Or is it tcp+http only?

**Comment by skoppe** [comment]
only connectTCP. But it would be trivial to implement. On the other hand you could wait for @s-ludwig to rewrite vibe, I bet its gonna support it.

**Comment by s-ludwig** [comment]
Should be possible for the 0.8.0-beta version with the `vibe-core` configuration for `vibe-d:core`. At least it's auto tested for the underlying `eventcore` library, just not yet in the vibe.d context.

**Comment by s-ludwig** [comment]
> The functionality seems to be in Phobos - does vibe.d wrap the same stuff?

No, vibe.d goes directly down to the OS APIs to avoid the overhead of the class based `std.socket` module where possible.

**Comment by liveresume** [comment]
@s-ludwig performance. always nice.  Will try beta out.  Just to confirm, `listenUDP()` should be possible with it?

**Comment by s-ludwig** [comment]
Hm, I just noticed that I forgot to merge the USDS related changes to `NetworkAddress`. Once that is done, `listenUDP` with a USDS `NetworkAddress` should work (the function will be renamed to `listenDatagram` later on).

**Comment by Geod24** [comment]
According to https://github.com/vibe-d/vibe.d/pull/1342#issuecomment-321856809 this is fixed and should be closed.
