### ISSUE TITLE
Disable Nagle's Algorithm in HTTP Server

### ISSUE THREAD

**Issue by etcimon** [vibe-d/vibe.d#569]
Flushing data packets on an HTTP server is currently hidden behind the mechanics of the kernel. I think the internal buffers in vibe are sufficiently mature to handle building decently sized packets. The flush() method doesn't currently guarantee sending a packet. 

So, would vibe be ready for handling this on its own?

**Comment by s-ludwig** [comment]
This has been enabled since quite a while: a16c54e540c64d8e284e1fe22164525197ce209e
