### ISSUE TITLE
Add all needed dependencies to the zip file that can be downloaded on vibed.org

### ISSUE THREAD

**Issue by s-ludwig** [vibe-d/vibe.d#571]
Currently, the download just contains the vibe.d sources. Having a zip file with all needed dependencies would better support using vibe.d for offline development. Ideal would be an installer that installs DUB and all packages to get a complete vibe.d development environment (excluding the compiler).

See also http://forum.rejectedsoftware.com/groups/rejectedsoftware.vibed/thread/12592/

**Comment by Geod24** [comment]
There is an (upstream) installer for DUB, and things work out of the box nowadays.
The ZIP file that is generated for release also contains the `lib/` directory, so I don't think there's anything else left here.
