### ISSUE TITLE
Add SPDY / HTTP/2.0 Support

### ISSUE THREAD

**Issue by etcimon** [vibe-d/vibe.d#665]
The [SPDY v3 / HTML 2 specs](http://www.chromium.org/spdy/spdy-protocol/spdy-protocol-draft3-1) are mostly the same, the specifications seem to indicate that a single connection must be kept alive and able to start new TCP Connection streams using a StreamID. 

To comply, a new Multiplexer object needs to be created which captures a single TCP Connection and forwards it to several TCP Connection handlers depending on the StreamID of the frame.

This is near the top on my todo list, because it can replace the need for websockets and at least chrome and firefox support it now.

**Comment by WebFreak001** [comment]
Any progress? I really want to support sending all the files my website needs to serve in a single repsonse because with polymer everything is really fragmented. With so many requests it takes about 5-15 seconds to load the page on localhost right now!

**Comment by s-ludwig** [comment]
I'll start to tackle this once 0.8.0 is out and any obvious issues have been resolved. It will happen in conjunction with some deeper changes in the HTML sub system, so depending on how much time I can devote, it will probably take a few months.

**Comment by Geod24** [comment]
This is being worked on as part of https://github.com/vibe-d/vibe-http so I'm going to close this as it is not actionable in here.
