### ISSUE TITLE
Automatically recompile and reload Diet templates in the background in development mode

### ISSUE THREAD

**Issue by s-ludwig** [vibe-d/vibe.d#676]
During development, a file system watcher could be used to monitor file changes in the Diet templates that make up the application. Each diet template, instead of being statically compiled into the application, would then be compiled as a separate shared library/DLL and dynamically loaded and unloaded as needed.

**Comment by Beyarz** [comment]
Any updates on this? @s-ludwig

**Comment by schveiguy** [comment]
FYI, anyone who wants to just make HTML changes to their diet templates can use the new live mode to avoid having to recompile. And it's much faster than a recompile.

See the latest diet-ng description here: https://github.com/rejectedsoftware/diet-ng#experimental-html-live-mode

I'm wondering if this issue shouldn't be moved to diet-ng (if not already) and closed here. An automatic recompile would be very nice intermediate step in addition to the live mode.

**Comment by Geod24** [comment]
Going to close this on account that:
- @schveiguy implemented the live-mode in diet-ng;
- This is a diet-ng issue (and in fact, I believe we should [reduce the dependency](https://github.com/vibe-d/vibe.d/issues/2361));
