### ISSUE TITLE
Commit dc61972 breaks mongo SSL connection

### ISSUE THREAD

**Issue by gittywithexcitement** [vibe-d/vibe.d#981]
When upgrading my app to the latest vibe.d, I encountered a change that caused my program to no longer be able to connect to mongodb over SSL. I narrowed the offending change down to commit dc61972b4c263263c947c01e9485ca1d2df81d61  
I'm using 
- mongo 2.4
- Ubuntu 14.04
- library versions that vibe.d specifies: libev-4.0.0_4.04, libevent-2.0.1_2.0.16, openssl-1.0.0_1.0.0e
- DMD64 v2.065.

I tried other commits beyond the offending one, namely 7.21-rc.3, 7.21, 7.22  All fail.

As stated, the problem is that attempts to connect to a mongodb server over SSL end in failure.

**Comment by dariusc93** [comment]
@gittywithexcitement  does it give an exception of some sort? I havent had issues with mongo but I am using 2.6, though that shouldnt be the issue. v2.066, Ubuntu 14.04 and Vibe 7.22 (though gonna push to master if #924 gets fix)

**Comment by Geod24** [comment]
Looking at HEAD and recent work (e.g. https://github.com/vibe-d/vibe.d/pull/2422), this issue has long been fixed.
